import test from 'node:test';import assert from 'node:assert/strict';import {scopedMessageStudents,familyMessageBatch} from '../src/utils/family-message-batch.mjs';import {weeklyReportPayload} from '../src/utils/weekly-report-delivery.mjs';
const classes=[{id:1,remoteId:'a',program:'bilingual',stage:'ابتدائي',grade:'خامس'},{id:2,remoteId:'b',program:'bilingual',stage:'ابتدائي',grade:'رابع'},{id:3,remoteId:'c',program:'diploma',stage:'ابتدائي',grade:'خامس'}];const students=[{id:1,remoteId:'one',classId:1,academicId:'9000000000'},{id:2,remoteId:'two',classId:2,academicId:'9000000001'},{id:3,remoteId:'one-diploma',classId:3,academicId:'9000000000'},{id:4,remoteId:'outside',classId:4,academicId:'9000000002'}];
test('grade, program and section intersections cannot include inaccessible classes and one child receives one message',async()=>{
 assert.equal(scopedMessageStudents(students,classes).length,2);assert.equal(scopedMessageStudents(students,classes,{program:'bilingual',grade:'ابتدائي|خامس'}).length,1);assert.equal(scopedMessageStudents(students,classes,{program:'bilingual',classIds:['c']}).length,0);
 const groups=scopedMessageStudents(students,classes,{classIds:['a']});const first=await familyMessageBatch(groups,'teacher','رسالة الصف','تذكير','batch');assert.equal(first.length,1);assert.equal(first[0].student_id,'one');assert.equal(first[0].kind,'تذكير');assert.deepEqual(await familyMessageBatch(groups,'teacher','رسالة الصف','تذكير','batch'),first);assert.notEqual((await familyMessageBatch(groups,'teacher','رسالة الصف','تذكير','new-batch'))[0].id,first[0].id);
});
test('weekly delivery freezes a complete isolated report and changes identity when full report content changes',async()=>{
 const files=[{studentIds:[1],name:'طالب.html',content:'<html>تقرير كامل</html>',messageText:'ملخص'}];const first=await weeklyReportPayload(files,students,'teacher','2026-10-04','2026-10-10');assert.equal(first[0].html,files[0].content);assert.equal(first[0].period_to,'2026-10-10');assert.deepEqual(await weeklyReportPayload(files,students,'teacher','2026-10-04','2026-10-10'),first);assert.notEqual((await weeklyReportPayload([{...files[0],content:'تقرير معدل'}],students,'teacher','2026-10-04','2026-10-10'))[0].id,first[0].id);
});
