begin;
do $test$
declare teacher uuid;family uuid;other_teacher uuid; own_student text;outside_student text; own_class text; message_id uuid;cert_id uuid;homework_id uuid;w jsonb; blocked boolean; result jsonb;newclass text;
begin
select user_id into teacher from public.profiles where full_name='عبد الرحمن علي نصر الله' and role='teacher';
select s.id,s.class_id,f.user_id into own_student,own_class,family from public.students s join public.teacher_class_assignments a on a.class_id=s.class_id join public.family_students f on f.student_id=s.id where a.teacher_id=teacher and s.active limit 1;
select s.id into outside_student from public.students s where not exists(select 1 from public.teacher_class_assignments a where a.teacher_id=teacher and a.class_id=s.class_id) and s.active limit 1;
select user_id into other_teacher from public.profiles where role='teacher' and user_id<>teacher limit 1;
if teacher is null or family is null or outside_student is null then raise exception 'Missing real scoped fixtures';end if;
perform public.teacher_management_commit(teacher,'student_archive',jsonb_build_object('id',own_student));
if(select active from public.students where id=own_student) then raise exception 'Archive failed';end if;
perform public.teacher_management_commit(teacher,'students_bulk_restore',jsonb_build_object('ids',jsonb_build_array(own_student)));
blocked:=false;begin perform public.teacher_management_commit(teacher,'students_bulk_archive',jsonb_build_object('ids',jsonb_build_array(own_student,outside_student)));exception when others then blocked:=true;end;
if not blocked or not(select active from public.students where id=own_student) then raise exception 'Bulk must rollback all unauthorized changes';end if;
blocked:=false;begin perform public.teacher_management_commit(teacher,'class_archive',jsonb_build_object('id',own_class));exception when others then blocked:=true;end;if not blocked then raise exception 'Occupied class archived';end if;
result:=public.teacher_management_commit(teacher,'class_save',jsonb_build_object('name','شعبة تحقق مؤقتة','section','اختبار-فقط','template_class',own_class));newclass:=result->>'id';
perform public.teacher_management_commit(teacher,'student_move',jsonb_build_object('id',own_student,'class_id',newclass));
if(select class_id from public.students where id=own_student)<>newclass then raise exception 'Move failed';end if;
perform public.teacher_management_commit(teacher,'student_move',jsonb_build_object('id',own_student,'class_id',own_class));
perform set_config('request.jwt.claims',jsonb_build_object('sub',teacher,'role','authenticated')::text,true);
execute 'set local role authenticated';
w:=public.teacher_workspace();if exists(select 1 from jsonb_array_elements(w->'students') s where s->>'id'=outside_student) then raise exception 'Workspace leaks other class';end if;
insert into public.teacher_student_notes(student_id,teacher_id,body) values(own_student,teacher,'ملاحظة تحقق ضمن معاملة ملغاة');
insert into public.school_private_messages(student_id,teacher_id,sender_id,body) values(own_student,teacher,teacher,'رسالة تحقق ضمن معاملة ملغاة') returning id into message_id;
blocked:=false;begin insert into public.school_private_messages(student_id,teacher_id,sender_id,body) values(own_student,teacher,family,'انتحال');exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception 'Sender spoofing allowed';end if;
insert into public.school_certificates(student_id,teacher_id,kind,title,achievement,body,teacher_name_snapshot,reference,issued_at) values(own_student,teacher,'تميز','تحقق غير منشور','إنجاز اختبار داخل معاملة ملغاة','تحقق غير منشور','اسم مزيف','FAKE','2000-01-01') returning id into cert_id;
if exists(select 1 from public.school_certificates where id=cert_id and (teacher_name_snapshot='اسم مزيف' or reference='FAKE' or issued_at<'2026-01-01')) then raise exception 'Certificate source can be forged';end if;
blocked:=false;begin update public.school_certificates set title='تغيير أصل الشهادة' where id=cert_id;exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception 'Certificate content mutable';end if;
insert into public.quran_homework(teacher_id,class_id,student_id,kind,title,instructions,due_date) values(teacher,own_class,own_student,'مقرأة','اختبار ملغى','داخل معاملة تحقق',current_date) returning id into homework_id;
update public.quran_homework set title='تعديل اختبار',cancelled=true where id=homework_id;
perform set_config('request.jwt.claims',jsonb_build_object('sub',family,'role','authenticated')::text,true);
if (select count(*) from public.teacher_student_notes)>0 then raise exception 'Parent sees private notes';end if;
if not exists(select 1 from public.school_private_messages where id=message_id) then raise exception 'Parent cannot see own message';end if;
insert into public.school_message_receipts(message_id,user_id) values(message_id,family);
if not exists(select 1 from public.school_certificates where id=cert_id) then raise exception 'Parent certificate missing';end if;
if not exists(select 1 from public.notifications where recipient_id=family and student_id=own_student and page='messages') then raise exception 'Message notification absent';end if;
blocked:=false;begin perform public.teacher_workspace();exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception 'Parent workspace allowed';end if;
blocked:=false;begin perform public.teacher_management_commit(teacher,'student_archive',jsonb_build_object('id',own_student));exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception 'Direct privileged RPC exposed';end if;
update public.school_certificates set revoked=true where id=cert_id;if found then raise exception 'Parent certificate write allowed';end if;
perform set_config('request.jwt.claims',jsonb_build_object('sub',other_teacher,'role','authenticated')::text,true);
if exists(select 1 from public.school_private_messages where id=message_id) then raise exception 'Other teacher sees private thread';end if;
if exists(select 1 from public.teacher_student_notes where student_id=own_student) then raise exception 'Other teacher sees personal notes';end if;
execute 'reset role';
end $test$;
select 'PASS: scoped management, atomic bulk, archive restore move, messages, receipts, private notes, certificates, parent read-only, homework notifications. All test writes rolled back.' as result;
rollback;