import {useState} from 'react';
import {useApp} from '../services/store';
import {supabase} from '../services/supabase';
import {Avatar,Button,Field,Panel} from '../components/ui';
export default function AccountPreferences(){
 const {user,db,refresh,notify}=useApp();const [avatar,setAvatar]=useState(user?.avatar||'');const [mode,setMode]=useState(db.settings.mode);const [font,setFont]=useState(db.settings.fontSize);const [density,setDensity]=useState(db.settings.density);const [motion,setMotion]=useState(Boolean(user?.reduceMotion));const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const image=async(file?:File)=>{if(!file)return;setError('');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){setError('اختر صورة JPG أو PNG أو WebP لا تتجاوز 5 ميغابايت.');return}setBusy(true);try{const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');canvas.width=canvas.height=240;const ctx=canvas.getContext('2d')!;const edge=Math.min(bitmap.width,bitmap.height);ctx.fillStyle='#ffffff';ctx.fillRect(0,0,240,240);ctx.drawImage(bitmap,(bitmap.width-edge)/2,(bitmap.height-edge)/2,edge,edge,0,0,240,240);bitmap.close();setAvatar(canvas.toDataURL('image/jpeg',.8))}catch{setError('تعذر قراءة الصورة. اختر صورة أخرى.')}finally{setBusy(false)}};
 const save=async()=>{if(!user)return;setBusy(true);setError('');try{const r=await supabase!.from('account_preferences').upsert({user_id:user.id,avatar,mode,font_size:font,density,reduce_motion:motion});if(r.error)throw r.error;await refresh();notify('تم حفظ صورة حسابك وتفضيلاتك')}catch{setError('تعذر حفظ التفضيلات. أعد المحاولة.')}finally{setBusy(false)}};
 return <Panel className="account-preferences"><h2>صورتي وراحة الاستخدام</h2><div className="row">{avatar?<img className="account-picture" src={avatar} alt="معاينة صورة حسابي"/>:<Avatar name={user?.name||''} size="large"/>}<div><Field label="تغيير صورة الحساب"><input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>void image(e.target.files?.[0])}/></Field><small>صورتك خاصة بحسابك، وتُحفظ بعد الضغط على حفظ.</small></div><Button disabled={busy||!avatar} onClick={()=>setAvatar('')}>إزالة الصورة</Button></div><div className="preferences-grid"><Field label="المظهر"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="dark">داكن</option><option value="light">فاتح</option><option value="system">حسب الجهاز</option></select></Field><Field label="حجم النص"><select value={font} onChange={e=>setFont(Number(e.target.value))}>{[14,16,18,20].map(n=><option key={n} value={n}>{n===14?'صغير':n===16?'متوسط':n===18?'كبير':'كبير جدًا'}</option>)}</select></Field><Field label="المسافات"><select value={density} onChange={e=>setDensity(e.target.value)}><option value="comfortable">مريحة</option><option value="compact">مختصرة</option></select></Field></div><label className="check-label"><input type="checkbox" checked={motion} onChange={e=>setMotion(e.target.checked)}/>تقليل الحركة والتأثيرات</label>{error&&<p role="alert" className="form-alert">{error}</p>}<div className="row"><Button variant="gold" disabled={busy} onClick={()=>void save()}>{busy?'جارٍ التجهيز…':'حفظ الصورة والتفضيلات'}</Button><Button disabled={busy} onClick={()=>{setMode('dark');setFont(16);setDensity('comfortable');setMotion(false)}}>استعادة العرض الافتراضي</Button></div></Panel>
}
