import {useMemo,useState} from 'react';
import {useApp,dateText} from '../services/store';
import {familyFollowupRows} from '../utils/family-followup.mjs';
import {riyadhDate} from '../utils/school-calendar.mjs';
import {Badge,Button,Empty,Field,PageTitle,Panel} from '../components/ui';
const labels:Record<string,string>={complete:'تابع الجميع',partial:'متابعة جزئية',pending:'لم يتابع',none:'لا يوجد مطلوب'};
export default function FamilyFollowups(){
 const {db,students,user,refresh,notify,selectStudent,navigate}=useApp();
 const [period,setPeriod]=useState('week'),[date,setDate]=useState(riyadhDate()),[program,setProgram]=useState(''),[classId,setClassId]=useState(''),[status,setStatus]=useState(''),[search,setSearch]=useState(''),[busy,setBusy]=useState(false);
 const day=new Date(date+'T12:00:00Z');const weekday=day.getUTCDay();const fromDay=new Date(day);fromDay.setUTCDate(day.getUTCDate()-weekday);const toDay=new Date(fromDay);toDay.setUTCDate(fromDay.getUTCDate()+6);
 const from=period==='all'?'':period==='day'?date:fromDay.toISOString().slice(0,10),to=period==='all'?'':period==='day'?date:toDay.toISOString().slice(0,10);
 const classes=db.classes.filter(c=>(!program||c.program===program)&&students.some(s=>s.classId===c.id));
 const scoped=useMemo(()=>students.filter(s=>(!program||s.program===program)&&(!classId||s.classId===Number(classId))),[students,program,classId]);
 const rows=useMemo(()=>familyFollowupRows(scoped,Object.values(db.evaluations),db.evaluationFollowups||[],db.quranHomework||[],db.homeworkFollowups||[],db.classes,{from,to}),[scoped,db.evaluations,db.evaluationFollowups,db.quranHomework,db.homeworkFollowups,db.classes,from,to]);
 const filtered=rows.filter(r=>(!status||r.status===status)&&(!search||r.student.name.includes(search)||r.student.parentName.includes(search))).sort((a,b)=>({pending:0,partial:1,complete:2,none:3}[a.status as 'pending']-({pending:0,partial:1,complete:2,none:3}[b.status as 'pending']))||a.student.name.localeCompare(b.student.name,'ar'));
 const due=rows.filter(r=>r.total),complete=rows.filter(r=>r.status==='complete').length,percentage=due.length?Math.round(complete/due.length*100):0;
 if(user?.role==='parent')return <Panel><Empty text="هذه الصفحة مخصصة لمتابعة المعلم لشعبه"/></Panel>;
 return <><PageTitle title="متابعة أولياء الأمور" subtitle="تأكيد الأسرة للتقييمات والواجبات الحالية، حسب اليوم أو الأسبوع" action={<Button disabled={busy} onClick={async()=>{setBusy(true);try{await refresh()}catch{notify('تعذر تحديث سجل متابعة الأسر')}finally{setBusy(false)}}}>{busy?'جارٍ التحديث…':'تحديث المتابعة'}</Button>}/>
 <Panel className="no-print"><div className="toolbar"><Field label="فترة متابعة الأسر"><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="day">اليوم المحدد</option><option value="week">الأسبوع المحدد</option><option value="all">كل السجل</option></select></Field>{period!=='all'&&<Field label="تاريخ متابعة الأسر"><input type="date" value={date} onChange={e=>e.target.value&&setDate(e.target.value)}/></Field>}<Field label="مسار متابعة الأسر"><select value={program} onChange={e=>{setProgram(e.target.value);setClassId('')}}><option value="">كل المسارات</option><option value="diploma">الدبلوما</option><option value="bilingual">ثنائي اللغة</option></select></Field><Field label="شعبة متابعة الأسر"><select value={classId} onChange={e=>setClassId(e.target.value)}><option value="">كل شعبي</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="البحث عن الطالب أو ولي الأمر"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="اكتب الاسم"/></Field><Button onClick={()=>window.print()}>طباعة كشف المتابعة</Button></div></Panel>
 <Panel><h2>{period==='all'?'كل السجل':from+' — '+to}</h2><p>{complete} من {due.length} طالبًا لديهم مطلوب تمت متابعتهم بالكامل • {percentage}%</p><small>المتابعة تأكيد صريح من الأسرة؛ فتح الصفحة وحده لا يُحتسب. تعديل التقييم أو الواجب يستلزم تأكيدًا جديدًا.</small></Panel>
 <div className="followup-status-grid no-print">{Object.entries(labels).map(([key,label])=><button aria-pressed={status===key} className={status===key?'active':''} key={key} onClick={()=>setStatus(status===key?'':key)}><b>{rows.filter(r=>r.status===key).length}</b><span>{label}</span></button>)}</div>
 <Panel><div className="section-head"><h2>{status?labels[status]:'جميع الأسر'} • {filtered.length}</h2>{status&&<Button onClick={()=>setStatus('')}>عرض الجميع</Button>}</div><div className="table-scroll"><table><thead><tr><th>الطالب / ولي الأمر</th><th>الشعبة</th><th>الحالة</th><th>التقييمات</th><th>الواجبات</th><th>المتبقي</th><th>آخر تأكيد</th><th className="no-print">المتابعة</th></tr></thead><tbody>{filtered.map(r=><tr key={r.student.id}><td><b>{r.student.name}</b><small className="followup-parent">{r.student.parentName||'ولي أمر الطالب'}</small></td><td>{db.classes.find(c=>c.id===r.student.classId)?.name}</td><td><Badge tone={r.status==='complete'?'green':r.status==='none'?'':'amber'}>{labels[r.status]}</Badge></td><td>{r.evaluationDone} / {r.evaluationTotal}</td><td>{r.homeworkDone} / {r.homeworkTotal}</td><td>{r.pending||'—'}</td><td>{r.last?dateText(r.last):'—'}</td><td className="no-print"><Button onClick={()=>{selectStudent(r.student.id);navigate('quran')}}>عرض الطالب</Button></td></tr>)}</tbody></table></div>{!filtered.length&&<Empty text="لا توجد نتائج مطابقة للفلاتر"/>}</Panel></>
}
