import {reportPeriod} from '../utils/report-period.mjs';
import {useState} from 'react';
import {useApp,dateText} from '../services/store';
import {supabase} from '../services/supabase';
import {Avatar,Badge,Button,Empty,Field,Panel,PageTitle} from '../components/ui';
import {calendarFocus,riyadhDate,dayIndex,isFollowed} from '../utils/school-calendar.mjs';
import type {QuranEvaluation} from '../types';
export function EvaluationResult({evaluation:e}:{evaluation:QuranEvaluation}){
 const {db,user,refresh,notify}=useApp();const [busy,setBusy]=useState(false);const followed=isFollowed(e,db.evaluationFollowups||[]);
 const follow=async()=>{if(!e.id)return;setBusy(true);try{const r=await supabase!.rpc('follow_evaluation',{target:e.id});if(r.error)throw r.error;await refresh();notify('تم تسجيل متابعة ولي الأمر')}catch{notify('تعذر تسجيل المتابعة، أعد المحاولة')}finally{setBusy(false)}};
 const plan=db.schoolPlans?.find(p=>p.id===e.planEntryId);
 return <div className="result-card"><div className="result-grade"><span>نتيجة المعلم • {e.track}</span><h2>{e.grade}</h2><strong>{e.scores[0]||'—'} <small>/ 5</small></strong><progress max={5} value={e.scores[0]||0}/></div>{plan&&<p className="result-assignment">{plan.text}</p>}<div className="result-detail"><h3>التقييم الكتابي</h3><p>{e.writtenFeedback||e.notes||'تم تسجيل مستوى الأداء، دون ملاحظة كتابية إضافية.'}</p>{e.writtenFeedback&&e.notes&&<p>{e.notes}</p>}{e.nextStep&&<div className="result-next"><b>الخطوة القادمة</b><p>{e.nextStep}</p></div>}{e.encouragement&&<p className="result-encourage">✦ {e.encouragement}</p>}<small>{e.teacherName||db.users.find(u=>u.id===e.teacherId)?.name||'معلم القرآن'} • {dateText(e.createdAt)}</small></div>{user?.role==='parent'?<Button variant={followed?'default':'gold'} disabled={busy||followed||!e.id} onClick={()=>void follow()}>{busy?'جارٍ التسجيل…':followed?'✓ تمت المتابعة':'تمت المتابعة'}</Button>:<Badge tone={followed?'green':'amber'}>{followed?'تابع ولي الأمر هذه النتيجة':'بانتظار متابعة ولي الأمر'}</Badge>}</div>
}
export default function FamilyOverview(){
 const {db,students,navigate,refresh,notify,studentId,selectStudent}=useApp();const [selected,setSelected]=useState(studentId||students[0]?.id||0);const s=students.find(s=>s.id===selected)||students[0];const [date,setDate]=useState(riyadhDate());const [busy,setBusy]=useState(false);const focus=calendarFocus(db.settings.termStartDate,date);const c=db.classes.find(c=>c.id===s?.classId);
 const all=Object.values(db.evaluations).filter(e=>e.studentId===s?.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const results=all.filter(e=>riyadhDate(e.createdAt)===date);const latest=all[0];const weekBounds=reportPeriod(date,'week');const weekResults=all.filter(e=>riyadhDate(e.createdAt)>=weekBounds.from&&riyadhDate(e.createdAt)<=weekBounds.to);const waiting=all.filter(e=>!isFollowed(e,db.evaluationFollowups||[]));const overdue=homeworkPending();function homeworkPending(){return (db.quranHomework||[]).filter(h=>!h.cancelled&&h.class_id===c?.remoteId&&(!h.student_id||h.student_id===s?.remoteId)&&h.due_date<=riyadhDate()&&!(db.homeworkFollowups||[]).some(f=>f.homework_id===h.id&&f.student_id===s?.remoteId&&f.homework_version===h.updated_at))} 
 const normalize=(v:string)=>v.replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/\s/g,'');
 const plans=(db.schoolPlans||[]).filter(p=>p.program===c?.program&&normalize(p.grade).includes(normalize(c?.grade||''))&&normalize(p.stage).includes(normalize(c?.stage||'').includes('متوسط')?'متوسط':normalize(c?.stage||'').includes('ثانو')?'ثانو':'ابتدا')&&p.week===focus.week&&dayIndex(p.day)===focus.day&&focus.schoolDay);
 const homework=(db.quranHomework||[]).filter(h=>!h.cancelled&&h.class_id===c?.remoteId&&(!h.student_id||h.student_id===s?.remoteId));
 if(!s)return <Empty text="لا يوجد طالب مرتبط بالحساب"/>;
 return <><PageTitle title="متابعة أبنائي" subtitle="نتيجة المعلم، والمطلوب، وخطوتك القادمة" action={<Button disabled={busy} onClick={async()=>{setBusy(true);try{await refresh()}catch{notify('تعذر التحديث')}finally{setBusy(false)}}}>تحديث المتابعة</Button>}/>
 <Panel className="family-focus"><div className="row"><Avatar name={s.name} size="large"/><div><h1>{s.name}</h1><small>{c?.name}</small></div></div><div className="toolbar"><Field label="الطالب والبرنامج"><select value={s.id} onChange={e=>{setSelected(Number(e.target.value));selectStudent(Number(e.target.value))}}>{students.map(s=><option key={s.id} value={s.id}>{s.name} • {s.program==='diploma'?'الدبلومة':'ثنائي اللغة'}</option>)}</select></Field><Field label="تاريخ المتابعة"><input type="date" value={date} onChange={e=>setDate(e.target.value||riyadhDate())}/></Field><Button onClick={()=>setDate(riyadhDate())}>اليوم</Button></div><div className="row"><Badge tone="gold">{focus.dayName}</Badge><Badge>{focus.inTerm?'الأسبوع '+focus.week:'خارج أسابيع الخطة'}</Badge><span>{new Date(date+'T12:00:00Z').toLocaleDateString('ar-SA',{dateStyle:'long',timeZone:'Asia/Riyadh'})}</span></div></Panel>
 <Panel className="family-quick-summary"><h2>خطوتك الآن</h2><div className="family-task-cards"><Button onClick={()=>{if(waiting[0])setDate(riyadhDate(waiting[0].createdAt))}} disabled={!waiting.length}>{waiting.length?waiting.length+' نتيجة تنتظر اطلاعك':'✓ نتائج المعلم تمت متابعتها'}</Button><Button onClick={()=>navigate('homework')}>{overdue.length?overdue.length+' واجب موعده اليوم أو قبله':'عرض واجبات المعلم'}</Button><Button onClick={()=>navigate('reader')}>التسميع والمصحف</Button></div><div className="family-week-strip" aria-label="أيام متابعة الأسبوع">{Array.from({length:7},(_,i)=>{const d=new Date(weekBounds.from+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+i);const key=d.toISOString().slice(0,10);const n=all.filter(e=>riyadhDate(e.createdAt)===key).length;return <button key={key} aria-pressed={date===key} onClick={()=>setDate(key)}><b>{d.toLocaleDateString('ar-SA',{weekday:'short',timeZone:'Asia/Riyadh'})}</b><span>{d.getUTCDate()}</span><small>{n?n+' تقييم':'لا تقييم'}</small></button>})}</div><small>اختر يومًا لعرض نتيجته؛ عدم وجود تقييم لا يعني غياب الطالب.</small></Panel>
 <div className="family-dashboard-grid"><Panel className="family-today"><h2>{date===riyadhDate()?'تقييم اليوم':'تقييم التاريخ المحدد'}</h2>{results.length?results.map(e=><EvaluationResult key={e.id||e.createdAt} evaluation={e}/>):<><Empty text="لم يرسل المعلم تقييمًا لهذا اليوم"/>{latest&&<details className="previous-result"><summary>آخر تقييم محفوظ • {dateText(latest.createdAt)}</summary><EvaluationResult evaluation={latest}/></details>}</>}</Panel>
 <div className="family-side"><Panel><h2>المطلوب لهذا اليوم</h2>{plans.length?plans.map(p=><div className="daily-assignment" key={p.id}><Badge>{p.track}</Badge><h3>{p.text}</h3></div>):<p>{!focus.inTerm?'هذا التاريخ خارج أسابيع الخطة المعتمدة.':focus.day>=5?'إجازة أسبوعية؛ لا يوجد مقرر مدرسي لهذا اليوم.':'لم يُعتمد مقرر لهذا اليوم.'}</p>}<Button onClick={()=>navigate('plans')}>الخطة الأسبوعية</Button></Panel><Panel><h2>واجبات المعلم</h2>{homework.length?homework.slice(0,4).map(h=><div className="daily-assignment" key={h.id}><Badge>{h.kind}</Badge><h3>{h.title}</h3><small>موعد المتابعة: {h.due_date} • {(db.homeworkFollowups||[]).some(f=>f.homework_id===h.id&&f.student_id===s.remoteId&&f.homework_version===h.updated_at)?'تمت المتابعة':'بانتظار المتابعة'}</small></div>):<p>لا توجد واجبات إضافية لهذا الطالب.</p>}<Button onClick={()=>navigate('homework')}>فتح الواجبات والمتابعة</Button></Panel></div></div>
 <div className="family-action-grid"><Button onClick={()=>navigate('messages')}>التواصل مع المعلم</Button><Button onClick={()=>navigate('certificates')}>شهادات ابني</Button><Button variant="gold" onClick={()=>navigate('reader')}>إرسال تسميع صوت أو فيديو</Button><Button onClick={()=>navigate('reports')}>التقرير الرسمي</Button><Button onClick={()=>navigate('leaderboard')}>نجوم غراس</Button><Button onClick={()=>navigate('review')}>سجل المتابعة</Button></div>
 <Panel><h2>ملخص أسبوع المتابعة</h2><div className="evaluation-stats"><div><small>تقييمات الأسبوع</small><h2>{weekResults.length}</h2></div><div><small>تسميعات بانتظار المعلم</small><h2>{db.recitations.filter(r=>r.studentId===s.id&&r.status==='pending').length}</h2></div><div><small>متابعات الأسرة المسجلة</small><h2>{weekResults.filter(e=>isFollowed(e,db.evaluationFollowups||[])).length}</h2></div></div></Panel></>
}