import {useEffect,useState} from 'react';
import WelcomeQuran from '../components/WelcomeQuran';
import {getPresentation} from '../services/presentation';
import {welcomeDefault,type WelcomeConfig} from '../data/welcome';
import {ArrowLeft,LoaderCircle,BookOpen,AudioLines,ChartNoAxesCombined,KeyRound} from 'lucide-react';
import {useApp} from '../services/store';
export default function Login(){
 const {login,db,authLoading}=useApp();const [code,setCode]=useState('');const [error,setError]=useState('');const [submitting,setSubmitting]=useState(false);const busy=authLoading||submitting;const [presentation,setPresentation]=useState<WelcomeConfig|null>(null);useEffect(()=>{let active=true;getPresentation().then(p=>active&&setPresentation(p)).catch(()=>active&&setPresentation(welcomeDefault));return()=>{active=false}},[]);const view=presentation||welcomeDefault;useEffect(()=>{if(presentation)document.title=presentation.platform_name},[presentation?.platform_name]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setError('');setSubmitting(true);try{const ok=await login(code,true);if(!ok)setError('تعذر الدخول. تحقق من الرقم والاتصال ثم أعد المحاولة.')}finally{setSubmitting(false)}};
 return <div data-reduce-motion={view.reduce_motion} className={'formal-login login-refined welcome-entrance '+(view.background_style==='gradient'?'login-gradient':'')}><header><a className="login-school-brand" href={view.school_site} target="_blank" rel="noopener noreferrer" aria-label={view.school_label}><img src={view.logo_data||db.settings.logo} alt={view.school_label}/></a><a className="login-school-link" href={view.school_site} target="_blank" rel="noopener noreferrer">موقع المدرسة <ArrowLeft size={16} aria-hidden="true"/></a></header>
 <main><section className="formal-login-title"><span className="login-kicker">{view.school_label}</span><h1>{view.platform_name}</h1><div className="login-gold-rule" aria-hidden="true"/><p>{view.login_subtitle}</p><div className="login-services"><span><BookOpen size={19}/> مصحف تفاعلي</span><span><AudioLines size={19}/> تسميع ومقرأة</span><span><ChartNoAxesCombined size={19}/> متابعة يومية</span></div>{presentation&&<WelcomeQuran config={presentation}/>}</section>
 <section className="formal-login-card" aria-labelledby="login-heading"><div className="login-card-heading"><span className="login-entry-icon" aria-hidden="true"><KeyRound size={24}/></span><h2 id="login-heading">تسجيل الدخول</h2><p>أهلًا بك في {view.platform_name}</p></div><form onSubmit={e=>void submit(e)}><label className="login-code-label" htmlFor="login-code">رقم الدخول</label><input id="login-code" required minLength={6} maxLength={12} inputMode="numeric" autoComplete="username" pattern="[0-9٠-٩۰-۹]*" dir="ltr" placeholder="أدخل رقم الدخول" disabled={busy} aria-invalid={Boolean(error)} aria-describedby={error?'login-code-help login-error':'login-code-help'} value={code} onChange={e=>{setCode(e.target.value.replace(/[۰-۹]/g,c=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(c))).replace(/[^0-9٠-٩]/g,''));setError('')}}/><p id="login-code-help" className="login-code-help">ولي الأمر: الرقم الوطني للطالب<br/>المعلم والمشرف: رقم الحساب</p>{error&&<p id="login-error" className="login-inline-error" role="alert">{error}</p>}<button className="login-submit" type="submit" disabled={busy||code.length<6}>{busy?<><LoaderCircle size={19} className="login-spinner" aria-hidden="true"/>جارٍ التحقق…</>:<>دخول <ArrowLeft size={19} aria-hidden="true"/></>}</button></form></section></main>
 <footer><span>{view.school_label}</span><span>© {new Date().getFullYear()} • {view.platform_name}</span></footer></div>
}
