import {useState} from 'react';
import {ArrowLeft,LoaderCircle} from 'lucide-react';
import {useApp} from '../services/store';
export default function Login(){
 const {login,db,authLoading}=useApp();const [code,setCode]=useState('');const [error,setError]=useState('');const [submitting,setSubmitting]=useState(false);const busy=authLoading||submitting;
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setError('');setSubmitting(true);try{const ok=await login(code,true);if(!ok)setError('تعذر الدخول. تحقق من الرقم والاتصال ثم أعد المحاولة.')}finally{setSubmitting(false)}};
 return <div className="formal-login login-refined"><header><a className="login-school-brand" href="https://www.gheras.edu.sa/" target="_blank" rel="noopener noreferrer" aria-label="مدارس غراس الأخلاق الأهلية"><img src={db.settings.logo} alt="مدارس غراس الأخلاق الأهلية"/></a><a className="login-school-link" href="https://www.gheras.edu.sa/" target="_blank" rel="noopener noreferrer">موقع المدرسة <ArrowLeft size={16} aria-hidden="true"/></a></header>
 <main><section className="formal-login-title"><span className="login-kicker">مدارس غراس الأخلاق الأهلية</span><h1>مقرأة غراس</h1><div className="login-gold-rule" aria-hidden="true"/><p>حفظٌ بإتقان، ومتابعةٌ باهتمام.</p></section>
 <section className="formal-login-card" aria-labelledby="login-heading"><div className="login-card-heading"><span className="login-card-rule" aria-hidden="true"/><h2 id="login-heading">تسجيل الدخول</h2></div><form onSubmit={e=>void submit(e)}><label className="login-code-label" htmlFor="login-code">رقم الدخول</label><input id="login-code" required minLength={6} maxLength={12} inputMode="numeric" autoComplete="username" pattern="[0-9٠-٩]*" dir="ltr" placeholder="أدخل رقم الدخول" disabled={busy} aria-invalid={Boolean(error)} aria-describedby={error?'login-code-help login-error':'login-code-help'} value={code} onChange={e=>{setCode(e.target.value.replace(/[^0-9٠-٩]/g,''));setError('')}}/><p id="login-code-help" className="login-code-help">الرقم الوطني للطالب أو رقم المعلم</p>{error&&<p id="login-error" className="login-inline-error" role="alert">{error}</p>}<button className="login-submit" type="submit" disabled={busy||code.length<6}>{busy?<><LoaderCircle size={19} className="login-spinner" aria-hidden="true"/>جارٍ التحقق…</>:<>دخول <ArrowLeft size={19} aria-hidden="true"/></>}</button></form></section></main>
 <footer><span>مدارس غراس الأخلاق الأهلية</span><span>© {new Date().getFullYear()} • مقرأة غراس</span></footer></div>
}