import RecitationRecorder from '../components/RecitationRecorder';
import {supabase} from '../services/supabase';
import {uploadCapacity,FALLBACK_UPLOAD_BYTES} from '../services/resumable-upload';
import TeacherMushaf from './TeacherMushaf';
import {useEffect,useState,useRef} from 'react';
import {BookOpen,ChevronLeft,FileAudio,Headphones,Mic,Pause,Play,Search,Send,Upload,Video,Volume2,CheckCircle2,Clock,Star,RotateCcw,ShieldCheck,AlertCircle} from 'lucide-react';
import {useApp,dateText} from '../services/store';
import {getMediaUrl} from '../services/media';
import {plans} from '../data/plans';
import {entriesForClass} from './SchoolQuran';
import {calendarFocus,dayIndex,feedbackFor} from '../utils/school-calendar.mjs';
import {quranSurahs,reciters} from '../data/quran';
import {evaluationKey,levels} from '../utils/domain.mjs';
import {Avatar,Badge,Button,Empty,Field,PageTitle,Panel,Progress,SectionHead} from '../components/ui';
import type {QuranEvaluation,RecitationSubmission} from '../types';

const ACTIVE_WEEK=6;
const gradeScores=[[5,5,5,5,5,5],[4,4,4,4,4,5],[3,3,3,3,3,4],[2,2,2,2,2,3],[1,1,1,1,1,2]];

export function Reader(){
 const {user,db,students}=useApp();if(!user)return null;
 const family=['parent','student'].includes(user.role);const [tab,setTab]=useState(family?'assignment':'mushaf');
 const ownIds=students.map(s=>s.id);const submissions=db.recitations.filter(r=>ownIds.includes(r.studentId));const pending=submissions.filter(r=>r.status==='pending');
 return <><PageTitle title="المقرأة والتسميع" subtitle={family?'واجب القرآن يصل تلقائيًا من الخطة، وارفع التسميع للمعلم من هنا':'استمع للتسميع ثم قيّمه مباشرة بضغطة واحدة'}/>
 <div className="maqraa-tabs segmented">{family&&<button className={tab==='assignment'?'active':''} onClick={()=>setTab('assignment')}><Mic size={17}/>واجبي والتسميع</button>}{!family&&<button className={tab==='inbox'?'active':''} onClick={()=>setTab('inbox')}><Headphones size={17}/>بانتظار التقييم <Badge tone="gold">{pending.length}</Badge></button>}<button className={tab==='mushaf'?'active':''} onClick={()=>setTab('mushaf')}><BookOpen size={17}/>المصحف التفاعلي</button></div>
 {tab==='assignment'&&(db.schoolPlans?<RemoteFamilyAssignment submissions={submissions}/>:<FamilyAssignment submissions={submissions}/>)} {tab==='inbox'&&<TeacherInbox submissions={submissions}/>} {tab==='mushaf'&&<TeacherMushaf/>}
 </>
}

function RemoteFamilyAssignment({submissions}:{submissions:RecitationSubmission[]}){
 const {db,students,submitRecitation,studentId,selectStudent}=useApp();const [selectedStudent,setSelectedStudent]=useState(studentId||students[0]?.id);const student=students.find(s=>s.id===selectedStudent)||students[0];
 const entries=entriesForClass(db.schoolPlans||[],db.classes.find(c=>c.id===student?.classId));
 const homework=(db.quranHomework||[]).filter(h=>!h.cancelled&&h.class_id===db.classes.find(c=>c.id===student?.classId)?.remoteId&&(!h.student_id||h.student_id===student?.remoteId));const [homeworkId,setHomeworkId]=useState('');const selectedHomework=homework.find(h=>h.id===homeworkId);const focus=calendarFocus(db.settings.termStartDate);const [entryId,setEntryId]=useState('');const entry=entries.find(x=>x.id===entryId)||entries.find(x=>x.week===focus.week&&dayIndex(x.day)===focus.day);
 const [surahId,setSurahId]=useState(1);const [from,setFrom]=useState(1);const [to,setTo]=useState(7);
 const [file,setFile]=useState<File|null>(null);const [sending,setSending]=useState(false);const [percent,setPercent]=useState(0);const [limit,setLimit]=useState(FALLBACK_UPLOAD_BYTES);const [previewUrl,setPreviewUrl]=useState('');const abort=useRef<AbortController|null>(null);useEffect(()=>{if(supabase)void uploadCapacity(supabase).then(setLimit).catch(()=>{})},[]);useEffect(()=>{if(!file){setPreviewUrl('');return}const u=URL.createObjectURL(file);setPreviewUrl(u);return()=>URL.revokeObjectURL(u)},[file]);useEffect(()=>()=>abort.current?.abort(),[]);
 if(!student)return <Empty/>;
 const send=async()=>{if(!file)return;setSending(true);setPercent(0);abort.current=new AbortController();const ok=await submitRecitation(file,{weekId:entry?.week||1,track:entry?.track==='تلاوة'?'التلاوة':'الحفظ',surah:selectedHomework?.title||entry?.text||quranSurahs[surahId-1].name,fromAyah:from,toAyah:to},student.id,{onProgress:setPercent,signal:abort.current.signal});if(ok)setFile(null);setSending(false)};
 return <div className="family-maqraa-layout"><Panel><h2>{student.name}</h2><Field label="البرنامج والصف"><select value={student.id} onChange={e=>{setSelectedStudent(Number(e.target.value));selectStudent(Number(e.target.value));setEntryId('');setHomeworkId('')}}>{students.map(s=><option key={s.id} value={s.id}>{db.classes.find(c=>c.id===s.classId)?.name}</option>)}</select></Field>{homework.length>0&&<Field label="واجب المعلم"><select value={homeworkId} onChange={e=>setHomeworkId(e.target.value)}><option value="">الخطة المدرسية / تسميع آخر</option>{homework.map(h=><option key={h.id} value={h.id}>{h.kind} • {h.title} • {h.due_date}</option>)}</select></Field>}{selectedHomework&&<p>{selectedHomework.instructions}</p>}{entries.length>0&&<Field label="اختيار مقرر آخر"><select value={entryId} onChange={e=>{setEntryId(e.target.value);setHomeworkId('')}}><option value="">مقرر اليوم الحالي</option>{entries.map(x=><option key={x.id} value={x.id}>الأسبوع {x.week} • {x.day} • {x.text}</option>)}</select></Field>}{entry?<Field label="المقرر من خطة المدرسة"><select value={entry.id} onChange={e=>setEntryId(e.target.value)}>{entries.map(x=><option key={x.id} value={x.id}>الأسبوع {x.week} • {x.day} • {x.text}</option>)}</select></Field>:<><p>لا يوجد مقرر مدرسي لهذا اليوم. اختر واجب المعلم أو مقررًا آخر أو سورة للتسميع.</p><Field label="السورة"><select value={surahId} onChange={e=>{const n=Number(e.target.value);setSurahId(n);setFrom(1);setTo(Math.min(7,quranSurahs[n-1].ayahs))}}>{quranSurahs.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field></>}
 <div className="two-grid"><Field label="من الآية"><input type="number" min="1" value={from} onChange={e=>setFrom(Math.max(1,Number(e.target.value)))}/></Field><Field label="إلى الآية"><input type="number" min={from} value={to} onChange={e=>setTo(Math.max(from,Number(e.target.value)))}/></Field></div>
 <RecitationRecorder onFile={setFile} limit={limit} disabled={sending}/><Field label="التسجيل الصوتي"><input type="file" accept="audio/mpeg,audio/mp4,audio/wav,audio/webm,.mp3,.m4a,.wav" disabled={sending} onChange={e=>setFile(e.target.files?.[0]||null)}/></Field><div className="recording-file-preview">{file&&<><p>{file.name} • {(file.size/1024/1024).toFixed(1)} ميغابايت</p>{file.size>limit?<p role="alert">الملف يتجاوز الحد الحالي: {Math.floor(limit/1024/1024)} ميغابايت.</p>:previewUrl&&(file.type.startsWith('audio/')?<audio controls preload="metadata" src={previewUrl}/>:<p role="alert">التسجيلات الصوتية فقط</p>)}<Button disabled={sending} onClick={()=>setFile(null)}>إزالة الملف</Button></>}</div>{sending&&<><Progress value={percent} label={percent===100?'جارٍ تسجيل الإرسال…':'تقدم الرفع'}/><Button onClick={()=>abort.current?.abort()}>إيقاف الرفع</Button></>}<Button variant="gold" disabled={!file||file.size>limit||sending} onClick={()=>void send()}>{sending?'جارٍ الرفع…':'إرسال إلى المعلم'}</Button><p>MP3 • M4A • WAV • WebM (صوت)<br/>الحد الحالي {Math.floor(limit/1024/1024)} ميغابايت • دعم 200 ميغابايت مجهّز لحين الترقية.</p></Panel><Panel><SectionHead title="تسميعاتي"/>{submissions.length?submissions.map(s=><SubmissionCard key={s.id} submission={s} readOnly/>):<Empty text="لا توجد تسجيلات مرسلة بعد"/>}</Panel></div>
}

function FamilyAssignment({submissions}:{submissions:RecitationSubmission[]}){
 const {students,submitRecitation}=useApp();const student=students[0];const plan=plans[ACTIVE_WEEK-1];const [track,setTrack]=useState<'الحفظ'|'التلاوة'>('الحفظ');const [file,setFile]=useState<File|null>(null);const [sending,setSending]=useState(false);const assignment=track==='الحفظ'?{surah:plan.memorization,from:plan.memFrom,to:plan.memTo}:{surah:plan.recitation,from:plan.recFrom,to:plan.recTo};if(!student)return <Empty/>;
 const send=async()=>{if(!file)return;setSending(true);const ok=await submitRecitation(file,{weekId:ACTIVE_WEEK,track,surah:assignment.surah,fromAyah:assignment.from,toAyah:assignment.to});if(ok)setFile(null);setSending(false)};
 return <div className="family-maqraa-layout"><Panel className="automatic-assignment"><div className="assignment-kicker"><Badge tone="green"><CheckCircle2 size={14}/>وصل تلقائيًا من الخطة</Badge><Badge>الأسبوع {ACTIVE_WEEK}</Badge></div><Avatar name={student.name} size="large"/><h2>{student.name}</h2><div className="segmented assignment-track"><button className={track==='الحفظ'?'active':''} onClick={()=>{setTrack('الحفظ');setFile(null)}}>الحفظ</button><button className={track==='التلاوة'?'active':''} onClick={()=>{setTrack('التلاوة');setFile(null)}}>التلاوة</button></div><div className="assignment-range"><BookOpen/><div><small>المطلوب</small><h1>سورة {assignment.surah}</h1><p>من الآية <b>{assignment.from}</b> إلى الآية <b>{assignment.to}</b></p></div></div><Progress value={submissions.some(s=>s.weekId===ACTIVE_WEEK&&s.track===track)?100:0} label={submissions.some(s=>s.weekId===ACTIVE_WEEK&&s.track===track)?'تم إرسال التسميع':'بانتظار رفع التسميع'}/><Button className="wide" onClick={()=>document.querySelector<HTMLInputElement>('#recitation-file')?.click()}><Upload size={17}/>اختر تسجيلًا صوتيًا</Button><input id="recitation-file" hidden type="file" accept="audio/*" onChange={e=>setFile(e.target.files?.[0]||null)}/>{file&&<div className="selected-recitation"><i><FileAudio/></i><div><b>{file.name}</b><small>{(file.size/1024/1024).toFixed(1)} ميجابايت</small></div><Button variant="gold" disabled={sending} onClick={send}><Send size={16}/>{sending?'جارٍ الإرسال':'إرسال للمعلم'}</Button></div>}<small className="upload-help">الصيغ الصوتية • الحد الحالي 50 ميغابايت • لا يمكن تعديل تقييم المعلم</small></Panel><Panel><SectionHead title="تسميعاتي" description="حالة الملفات المرسلة وملاحظات المعلم"/>{submissions.length?submissions.slice(0,8).map(s=><SubmissionCard key={s.id} submission={s} readOnly/>):<Empty text="لم يُرفع تسميع بعد"/>}</Panel></div>
}

function TeacherInbox({submissions}:{submissions:RecitationSubmission[]}){
 const [filter,setFilter]=useState<'pending'|'reviewed'>('pending');const rows=submissions.filter(s=>s.status===filter);
 return <><div className="inbox-summary"><Panel><Clock/><div><b>{submissions.filter(s=>s.status==='pending').length}</b><span>بانتظار التقييم</span></div></Panel><Panel><CheckCircle2/><div><b>{submissions.filter(s=>s.status==='reviewed').length}</b><span>تم تقييمها</span></div></Panel><div className="segmented"><button className={filter==='pending'?'active':''} onClick={()=>setFilter('pending')}>الجديدة أولًا</button><button className={filter==='reviewed'?'active':''} onClick={()=>setFilter('reviewed')}>تم تقييمها</button></div></div><div className="submission-grid">{rows.map(s=><SubmissionCard key={s.id} submission={s}/>)}</div>{!rows.length&&<Panel><Empty text={filter==='pending'?'لا توجد تسميعات جديدة؛ اكتملت القائمة':'لا توجد تقييمات محفوظة بعد'}/></Panel>}</>
}

function SubmissionCard({submission,readOnly=false}:{submission:RecitationSubmission;readOnly?:boolean}){
 const {db,user,students,mutate}=useApp();const [url,setUrl]=useState('');const [notes,setNotes]=useState(submission.teacherNotes||'');const [saving,setSaving]=useState(false);const student=students.find(s=>s.id===submission.studentId)||db.students.find(s=>s.id===submission.studentId);
 useEffect(()=>{let active=true;let objectUrl='';getMediaUrl(submission.id).then(value=>{objectUrl=value;if(active)setUrl(value)});return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl)}},[submission.id]);
 const evaluate=(grade:string,index:number)=>{if(readOnly||!user)return;setSaving(true);const day=calendarFocus(db.settings.termStartDate).day;const feedback=feedbackFor(student?.name||'الطالب',5-index,submission.studentId);const value:QuranEvaluation={...feedback,studentId:submission.studentId,weekId:submission.weekId,day,track:submission.track,grade,scores:gradeScores[index],self:[],review:[],notes:notes.trim()||`تم تقييم التسميع المرسل: ${submission.surah} ${submission.fromAyah}–${submission.toAyah}.`,teacherId:user.id,createdAt:new Date().toISOString()};mutate(`تم تقييم تسميع ${student?.name||'الطالب'}`,d=>{const item=d.recitations.find(r=>r.id===submission.id)!;item.status='reviewed';item.grade=grade;item.teacherNotes=value.notes;item.evaluatedAt=value.createdAt;item.evaluatedBy=user.id;d.evaluations[evaluationKey(submission.studentId,submission.weekId,day,submission.track)]=value;d.notifications.unshift({id:crypto.randomUUID(),studentId:submission.studentId,title:`تم تقييم تسميع ${submission.track}: ${grade}`,page:'reader',readBy:[],date:value.createdAt})},'evaluation',submission.studentId);setSaving(false)};
 return <Panel className="submission-card"><div className="submission-head"><div><Avatar name={student?.name||'طالب'}/><span><b>{student?.name}</b><small>{dateText(submission.submittedAt)}</small></span></div><Badge tone={submission.status==='reviewed'?'green':'gold'}>{submission.status==='reviewed'?'تم التقييم':'بانتظار التقييم'}</Badge></div><div className="submission-assignment"><b>{submission.track} • سورة {submission.surah}</b><span>{submission.fromAyah}–{submission.toAyah}</span></div>{url?(submission.mimeType.startsWith('video/')?<video className="submission-media" controls preload="metadata" src={url}/>:<audio className="submission-audio" controls preload="metadata" src={url}/>):<div className="media-loading"><Headphones/><span>جارٍ تجهيز التسجيل...</span></div>}{submission.status==='reviewed'?<div className="review-result"><Badge tone="green">{submission.grade}</Badge><p>{submission.teacherNotes}</p></div>:!readOnly&&<><Field label="ملاحظة قصيرة — اختيارية"><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="مثال: تحسن واضح في مخارج الحروف"/></Field><div className="inline-grades">{levels.map((grade,index)=>{const Icon=[Star,CheckCircle2,ShieldCheck,AlertCircle,RotateCcw][index];return <button disabled={saving} key={grade} onClick={()=>evaluate(grade,index)}><Icon size={18}/><span>{grade}</span></button>})}</div><small className="one-tap-hint">الضغط على المستوى يحفظ التقييم ويرسل الملخص لولي الأمر مباشرة.</small></>}</Panel>
}

