import "../styles/plan-details.css";
import {useState} from 'react';
import {useApp} from '../services/store';
import {supabase} from '../services/supabase';
import {entriesForClass} from '../utils/plan-entries.mjs';
import {calendarFocus,schoolDays,riyadhDate,dayIndex} from '../utils/school-calendar.mjs';
import {schoolDateLabel} from '../utils/report-period.mjs';
import {assignmentDetails,detailedPlanWeek} from '../utils/plan-details.mjs';
import {sourcePlanSummaries} from '../data/source-plan-summaries';
import {Badge,Button,Empty,Field,PageTitle,Panel,Modal} from '../components/ui';
import type {SchoolPlanEntry} from '../types';

export default function SchoolPlans(){
 const {db,students,navigate,user,refresh,notify}=useApp();
 const staff=['admin','principal','supervisor','teacher'].includes(user?.role||'');
 const classes=db.classes.filter(c=>students.some(s=>s.classId===c.id));
 const [classId,setClassId]=useState(classes[0]?.id||0);
 const focus=calendarFocus(db.settings.termStartDate);
 const [week,setWeek]=useState(focus.week);const [wholeTerm,setWholeTerm]=useState(false);
 const [editing,setEditing]=useState<{id:string;text:string}|null>(null);const [saving,setSaving]=useState(false);
 const classroom=classes.find(c=>c.id===classId)||classes[0];
 const entries=entriesForClass(db.schoolPlans||[],classroom);
 const normalize=(v:string)=>v.replace(/[أإآ]/g,'ا').replace(/\s/g,'');
 const source=classroom?.stage?.includes('ابتدا')?Object.entries(sourcePlanSummaries).find(([grade])=>normalize(grade).includes(normalize(classroom.grade||'__')))?.[1]:undefined;
 const reviewNotes=(number:number)=>{
  const grade=normalize(classroom?.grade||'');const middle=classroom?.stage?.includes('متوسط');
  if(middle&&grade.includes('اول')&&number===4)return 'الأربعاء: المصدر يذكر 106–11؛ النطاق معكوس ويحتاج تصحيحًا معتمدًا.';
  if(middle&&grade.includes('اول')&&number===5)return 'الآيتان 12 و13 من سورة النحل غير مذكورتين بين مقرري الأحد والاثنين في الاستمارة؛ راجع توزيع الشعبة.';
  if(!middle&&grade.includes('ثاني')&&number===7)return 'توجد آيات مشتركة عند حدود 30–36، ثم 36–40، ثم 40–46 في الاستمارة. راجع هل التداخل مقصود للمراجعة.';
  if(!middle&&grade.includes('رابع')&&number===2)return 'رأس السورة يذكر 24–45، وأول يوم يبدأ من 23 في الاستمارة؛ راجع بداية مقرر الأحد.';
  return '';
 };
 const save=async()=>{if(!editing?.text.trim()||!classroom?.remoteId||!supabase)return;setSaving(true);try{const r=await supabase.rpc('save_class_plan',{class_ref:classroom.remoteId,entry_ref:editing.id,assignment:editing.text.trim()});if(r.error)throw r.error;await refresh();setEditing(null);notify('تم تحديث خطة الشعبة للمعلم وولي الأمر')}catch{notify('تعذر تحديث المقرر، أعد المحاولة')}finally{setSaving(false)}};
 const assignment=(entry:SchoolPlanEntry)=>{const details=assignmentDetails(entry.text);return <div className="plan-assignment" key={entry.id+entry.classId}><div className="row"><Badge tone={details.review?'green':'gold'}>{entry.track}</Badge><small>{details.kind}</small>{entry.classId&&<Badge>تعديل معلم الشعبة</Badge>}</div><h3>{entry.text}</h3>{details.count!==undefined&&!details.review&&<p>{dayIndex(entry.day)<0?'نطاق الأسبوع':'نطاق اليوم'}: من الآية <b>{details.from}</b> إلى <b>{details.to}</b> • <b>{details.count}</b> آيات</p>}{details.invalid&&<p className="plan-source-warning">نطاق الآيات في المصدر غير متسلسل؛ يحتاج اعتماد التصحيح من المعلم.</p>}{staff&&<Button className="no-print" onClick={()=>setEditing({id:entry.id,text:entry.text})}>تعديل مقرر الشعبة</Button>}</div>};
 const renderWeek=(number:number)=>{const plan=detailedPlanWeek(entries,number,db.settings.termStartDate);const summary=source?.weeks[number-1];return <section className="detailed-plan-week" key={number}><Panel className="plan-week-heading"><div className="section-head"><h2>الأسبوع {number}</h2>{number===focus.week&&focus.inTerm&&<Badge tone="gold">الأسبوع الحالي</Badge>}</div><p>{schoolDateLabel(plan.from)}<br/>إلى {schoolDateLabel(plan.to)}</p>{summary&&<div className="plan-source-summary"><b>مقرر الأسبوع في توزيع المدرسة</b><p>الحفظ: {summary[0]}</p>{summary[1]&&<p>التلاوة: {summary[1]}</p>}<small>المصدر: {source.source} • التوزيع اليومي أدناه من الاستمارة وتعديلات معلم الشعبة.</small></div>}{staff&&reviewNotes(number)&&<p className="plan-source-warning"><b>ملاحظة لمراجعة المصدر:</b> {reviewNotes(number)}</p>}{number===13&&<p className="plan-calendar-note">بعد هذا الأسبوع: إجازة الخريف من 20 إلى 28 نوفمبر، واستئناف الأسبوع 14 يوم 29 نوفمبر.</p>}</Panel><div className="plan-days-grid">{plan.days.map(day=><Panel key={day.date} className={'plan-day '+(day.date===riyadhDate()?'plan-day-current':'')}><div className="section-head"><h3>{schoolDays[day.day]}</h3>{day.date===riyadhDate()&&<Badge tone="gold">اليوم</Badge>}</div><small>{schoolDateLabel(day.date)}</small>{day.holiday?<p className="plan-calendar-note">{day.holiday} • لا يوجد واجب مدرسي جديد في هذا اليوم.</p>:day.entries.length?day.entries.map(assignment):<Empty text="لم يُحدد مقرر يومي في المصدر؛ يعتمد المعلم المطلوب"/>}</Panel>)}</div>{plan.weekly.length>0&&<Panel className="plan-weekly-recitation"><h3>مقرر التلاوة أو المراجعة الأسبوعي</h3><p>يخص الأسبوع كاملًا؛ لم يحدد المصدر تقسيمًا يوميًا له.</p>{plan.weekly.map(assignment)}</Panel>}<Panel className="plan-practice-guide"><details><summary>خطوات متابعة المقرر في المنزل</summary><ol><li>افتح مصحف المنصة واستمع إلى المقرر المحدد من المعلم.</li><li>كرر الآيات مع القارئ، ثم حاول التسميع دون النظر.</li><li>راجع ما سبق قبل إضافة الحفظ الجديد.</li><li>أرسل تسجيلًا صوتيًا إذا طلب المعلم، ثم اطلع على تقييمه وتوجيهه.</li></ol><small>خطوات مساعدة للأسرة؛ مقدار الحفظ المعتمد هو المقرر الموضح أعلاه.</small></details></Panel></section>};
 return <><PageTitle title="الخطة التفصيلية والواجب" subtitle="المقرر اليومي والأسبوعي بتواريخ ميلادية وهجرية"/><Panel className="no-print"><div className="toolbar"><Field label="البرنامج والصف والشعبة"><select value={classroom?.id||0} onChange={e=>setClassId(Number(e.target.value))}>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="الأسبوع"><select value={week} onChange={e=>{setWeek(Number(e.target.value));setWholeTerm(false)}}>{Array.from({length:17},(_,i)=>i+1).map(w=><option key={w} value={w}>الأسبوع {w} {w===focus.week&&focus.inTerm?'• الحالي':''}</option>)}</select></Field><Button onClick={()=>{setWeek(focus.week);setWholeTerm(false)}}>الأسبوع الحالي</Button><Button onClick={()=>setWholeTerm(!wholeTerm)}>{wholeTerm?'عرض أسبوع واحد':'عرض الفصل كاملًا'}</Button><Button onClick={()=>window.print()}>طباعة الخطة</Button><Button variant="gold" onClick={()=>navigate('reader')}>المصحف والتسميع</Button></div>{focus.holiday&&<p>{focus.holiday} • {schoolDateLabel(focus.date)}</p>}</Panel><div className="plan-print-header"><img src={db.settings.logo} alt="شعار المدرسة"/><div><h2>{db.settings.school}</h2><h3>{classroom?.name}</h3><p>{db.settings.term} • {db.settings.year} هـ</p></div></div>{classroom?(wholeTerm?Array.from({length:17},(_,i)=>renderWeek(i+1)):renderWeek(week)):<Panel><Empty text="لا توجد شعبة مرتبطة بالحساب"/></Panel>}<Panel><h3>مواعيد ختام الفصل حسب توزيع المدرسة</h3><p>27–31 ديسمبر 2026: اختبارات شفهية وعملية.</p><p>3–7 يناير 2027: اختبارات نهائية.</p><p>8–16 يناير 2027: إجازة منتصف العام.</p></Panel>{editing&&<Modal title="تعديل مقرر الشعبة" onClose={()=>!saving&&setEditing(null)}><p>يظهر التعديل في شعبتك لدى المعلم والأسرة، وتبقى الاستمارة الأصلية محفوظة.</p><Field label="السورة ونطاق الآيات أو المطلوب"><textarea rows={5} maxLength={2000} value={editing.text} onChange={e=>setEditing({...editing,text:e.target.value})}/></Field><Button variant="gold" disabled={saving||!editing.text.trim()} onClick={()=>void save()}>حفظ المقرر</Button></Modal>}</>;
}
