import AccountPreferences from './AccountPreferences';
import {useEffect,useState} from 'react';
import FamilyOverview,{EvaluationResult} from './FamilyOverview';
import {calendarFocus,isFollowed} from '../utils/school-calendar.mjs';
import {useApp,dateText} from '../services/store';
import {supabase} from '../services/supabase';
import {entriesForClass} from './SchoolQuran';
import {Avatar,Badge,Button,Empty,Field,PageTitle,Panel,Modal} from '../components/ui';
import {BookOpen,ClipboardList,Trophy,AudioLines,CalendarDays,Bell} from 'lucide-react';
export function SchoolHome(){const {user}=useApp();return user?.role==='parent'?<FamilyOverview/>:<TeacherHome/>}
function TeacherHome(){const {db,user,students,navigate}=useApp();const family=user?.role==='parent';const evaluations=Object.values(db.evaluations);const today=evaluations.filter(e=>todayKey(e.createdAt)===todayKey(new Date().toISOString()));const pending=db.recitations.filter(r=>r.status==='pending').length;return <><PageTitle title={family?'متابعة أبنائي':'مقرأة غراس'} subtitle={family?'الخطة والتسميع ونتائج المتابعة':'متابعة شعبك وطلابك'}/><Panel className="home-school-banner"><img src={db.settings.logo} alt="مدارس غراس الأخلاق"/><div><h2>{user?.name}</h2><p>{family?'شراكة الأسرة في رحلة القرآن':'لكل طالب خطوة، ولكل إنجاز متابعة'}</p></div></Panel><div className="stat-grid school-home-stats"><Panel><small>{family?'البرامج المرتبطة':'الطلاب'}</small><h2>{family?db.classes.length:students.length}</h2></Panel><Panel><small>متابعات اليوم</small><h2>{today.length}</h2></Panel><Panel><small>التسميعات الجديدة</small><h2>{pending}</h2></Panel></div><div className="school-shortcuts">{[{id:'quran',label:family?'متابعة القرآن':'التقييم السريع',icon:ClipboardList},{id:'plans',label:'الخطة والواجب',icon:CalendarDays},{id:'reader',label:'المقرأة والمصحف',icon:BookOpen},{id:'review',label:'متابعة اليوم',icon:AudioLines},{id:'leaderboard',label:'نجوم غراس',icon:Trophy},{id:'notifications',label:'الإشعارات',icon:Bell},{id:'management',label:'إدارة طلابي وشعبي',icon:ClipboardList},{id:'homework',label:'إدارة الواجبات',icon:CalendarDays},{id:'reports',label:'طباعة التقارير',icon:ClipboardList},{id:'profile',label:'حسابي ومظهر المنصة',icon:BookOpen},{id:'messages',label:'التواصل الخاص',icon:Bell},{id:'certificates',label:'شهادات الطلاب',icon:Trophy}].map(a=><button key={a.id} onClick={()=>navigate(a.id)}><a.icon/><b>{a.label}</b><span>←</span></button>)}</div>{family&&<div className="two-grid">{students.map(s=>{const latest=today.filter(e=>e.studentId===s.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];return <Panel key={s.id}><div className="row"><Avatar name={s.name}/><div><h3>{s.name}</h3><small>{db.classes.find(c=>c.id===s.classId)?.name}</small></div></div><Badge tone="gold">{latest?.grade||'لا يوجد تقييم اليوم'}</Badge><p>{latest?.notes||'تظهر نتيجة اليوم وملاحظة المعلم فور إرسالها'}</p><Button onClick={()=>navigate('plans')}>عرض المطلوب</Button></Panel>})}</div>}</>}
export function SchoolPlans(){const {db,students,navigate,user,refresh,notify}=useApp();const leadership=['admin','principal','supervisor'].includes(user?.role||'');const [editing,setEditing]=useState<{id:string;text:string}|null>(null);const [saving,setSaving]=useState(false);const editPlan=async()=>{if(!editing?.text.trim())return;setSaving(true);try{const result=await supabase!.from('quran_plan_entries').update({assignment_text:editing.text.trim()}).eq('id',editing.id).select('id');if(result.error||result.data?.length!==1)throw Error();await refresh();setEditing(null);notify('تم تحديث المقرر')}catch{notify('تعذر تحديث المقرر')}finally{setSaving(false)}};const classes=db.classes.filter(c=>students.some(s=>s.classId===c.id));const [classId,setClassId]=useState(classes[0]?.id||0);const [week,setWeek]=useState(calendarFocus(db.settings.termStartDate).week);const classroom=classes.find(c=>c.id===classId)||classes[0];const entries=entriesForClass(db.schoolPlans||[],classroom).filter(e=>e.week===week);return <><PageTitle title="الخطة والواجب" subtitle="المقررات المعتمدة من استمارات المدرسة"/><Panel><div className="toolbar"><Field label="البرنامج والصف"><select value={classroom?.id||0} onChange={e=>setClassId(Number(e.target.value))}>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="الأسبوع"><select value={week} onChange={e=>setWeek(Number(e.target.value))}>{Array.from({length:17},(_,i)=>i+1).map(w=><option key={w} value={w}>الأسبوع {w}</option>)}</select></Field><Button onClick={()=>window.print()}>طباعة الخطة</Button><Button variant="gold" onClick={()=>navigate('reader')}>فتح التسميع والمصحف</Button></div></Panel><div className="plans-grid">{entries.map(e=><Panel key={e.id}><Badge tone="gold">{e.track}</Badge><h3>{e.day}</h3><h2>{e.text}</h2>{leadership&&<Button onClick={()=>setEditing({id:e.id,text:e.text})}>تعديل المقرر</Button>}</Panel>)}</div>{!entries.length&&<Panel><Empty text="لم يُعتمد مقرر لهذا الأسبوع"/></Panel>}{editing&&<Modal title="تعديل المقرر" onClose={()=>!saving&&setEditing(null)}><Field label="المقرر"><textarea rows={3} required maxLength={2000} value={editing.text} onChange={e=>setEditing({...editing,text:e.target.value})}/></Field><Button variant="gold" disabled={saving||!editing.text.trim()} onClick={()=>void editPlan()}>حفظ المقرر</Button></Modal>}</>}
function todayKey(value:string){return new Date(value).toLocaleDateString('en-CA',{timeZone:'Asia/Riyadh'})}
export function SchoolHistory(){
 const {db,students,page,refresh,notify}=useApp();const [studentId,setStudentId]=useState(0);const [classId,setClassId]=useState(0);const [track,setTrack]=useState('');const [period,setPeriod]=useState('today');const [date,setDate]=useState(todayKey(new Date().toISOString()));const [busy,setBusy]=useState(false);const [from,setFrom]=useState(date);const [to,setTo]=useState(date);const report=page==='reports';
 const rows=Object.values(db.evaluations).filter(e=>{const s=students.find(s=>s.id===e.studentId);const d=todayKey(e.createdAt);return (!studentId||s?.id===studentId)&&(!classId||s?.classId===classId)&&(!track||e.track===track)&&(period==='all'||period==='range'&&d>=from&&d<=to||period==='today'&&d===date)}).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
 const average=rows.length?(rows.reduce((sum,e)=>sum+(Number(e.scores[0])||0),0)/rows.length).toFixed(1):'—';
 const caption=period==='all'?'جميع المتابعات المسجلة':period==='range'?from+' إلى '+to:date;
 return <><PageTitle title={report?'التقرير الرسمي للمتابعة':'سجل المتابعة'} subtitle="النتائج الفعلية وملاحظات المعلم ومتابعة الأسرة" action={<Button disabled={busy} onClick={async()=>{setBusy(true);try{await refresh()}catch{notify('تعذر تحديث المتابعة')}finally{setBusy(false)}}}>تحديث</Button>}/><Panel className="no-print"><div className="toolbar"><Field label="الشعبة"><select value={classId} onChange={e=>{setClassId(Number(e.target.value));setStudentId(0)}}><option value={0}>جميع الشعب المتاحة</option>{db.classes.filter(c=>students.some(s=>s.classId===c.id)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="الطالب"><select value={studentId} onChange={e=>setStudentId(Number(e.target.value))}><option value={0}>كل الطلاب المرتبطين</option>{students.filter(s=>!classId||s.classId===classId).map(s=><option key={s.id} value={s.id}>{s.name} • {s.program==='diploma'?'الدبلومة':'ثنائي اللغة'}</option>)}</select></Field><Field label="الفترة"><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="today">تقرير يومي</option><option value="range">فترة محددة</option><option value="all">كل المتابعة</option></select></Field>{period==='today'&&<Field label="تاريخ التقرير"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field>}{period==='range'&&<><Field label="من"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="إلى"><input type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></Field></>}<Field label="المسار"><select value={track} onChange={e=>setTrack(e.target.value)}><option value="">كل المسارات</option><option>الحفظ</option><option>التلاوة</option></select></Field><Button variant="gold" onClick={()=>window.print()}>طباعة / حفظ PDF</Button></div></Panel>
 <article className={'official-report '+(!report?'print-only-report':'')}><header className="official-header"><div className="official-logo"><img src={db.settings.logo} alt="شعار المدرسة"/></div><div><h2>{db.settings.school}</h2><h1>تقرير متابعة القرآن الكريم</h1><p>مقرأة غراس • {db.settings.term} • {db.settings.year} هـ</p></div></header><div className="official-meta"><span>فترة التقرير: {caption}</span><span>تاريخ الإصدار: {new Date().toLocaleDateString('ar-SA',{timeZone:'Asia/Riyadh'})}</span><span>النتائج: {rows.length} • الطلاب: {new Set(rows.map(e=>e.studentId)).size}</span><span>متوسط الأداء: {average} / 5</span></div>{rows.map(e=>{const s=students.find(s=>s.id===e.studentId);const c=db.classes.find(c=>c.id===s?.classId);const plan=db.schoolPlans?.find(p=>p.id===e.planEntryId);return <section className="official-result" key={e.id||e.createdAt}><div className="official-result-heading"><h3>{s?.name}</h3><b>{e.grade} • {e.scores[0]} / 5</b></div><p>{c?.name} • {e.track} • الأسبوع {e.weekId}</p><table><tbody><tr><th>المقرر</th><td>{plan?.text||'تسميع القرآن الكريم'}</td></tr><tr><th>التقييم الكتابي</th><td>{e.writtenFeedback||e.notes||'لم تُسجل ملاحظة كتابية إضافية'}{e.writtenFeedback&&e.notes&&<p>{e.notes}</p>}</td></tr>{e.nextStep&&<tr><th>الخطوة القادمة</th><td>{e.nextStep}</td></tr>}{e.encouragement&&<tr><th>التشجيع</th><td>{e.encouragement}</td></tr>}<tr><th>المعلم / التاريخ</th><td>{e.teacherName||db.users.find(u=>u.id===e.teacherId)?.name||'معلم القرآن'} • {dateText(e.createdAt)}</td></tr><tr><th>متابعة ولي الأمر</th><td>{isFollowed(e,db.evaluationFollowups||[])?'تمت متابعة النتيجة الحالية':'بانتظار المتابعة'}</td></tr></tbody></table></section>})}{!rows.length&&<p className="official-empty">لا توجد تقييمات محفوظة للفترة المحددة.</p>}<footer className="official-footer"><p>صدر التقرير من سجلات مقرأة غراس؛ يتضمن النتائج المحفوظة للفترة المحددة.</p><div><span>توقيع المعلم: ................................</span><span>اعتماد المشرف: ................................</span></div></footer></article>
 {!report&&<><div className="history-cards">{rows.map(e=><Panel key={e.id||e.createdAt}><div className="row"><Avatar name={students.find(s=>s.id===e.studentId)?.name||''}/><h3>{students.find(s=>s.id===e.studentId)?.name}</h3><Badge>الأسبوع {e.weekId}</Badge></div><EvaluationResult evaluation={e}/></Panel>)}</div>{!rows.length&&<Panel><Empty text="لا توجد تقييمات محفوظة لهذه الفترة"/></Panel>}</>}
 </>;
}
type Star={display_name:string;program_id:string;class_name:string;points:number;evaluation_count:number;rank_number:number};
export function SchoolStars(){const [rows,setRows]=useState<Star[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const load=async()=>{setLoading(true);setError(false);const r=await supabase?.rpc('quran_stars');if(r?.error)setError(true);else setRows(r?.data||[]);setLoading(false)};useEffect(()=>{void load()},[]);return <><PageTitle title="نجوم غراس" subtitle="لوحة التميّز لآخر سبعة أيام" action={<Button onClick={()=>void load()}>تحديث</Button>}/><Panel className="stars-intro"><Trophy size={42}/><div><h2>كل خطوة في القرآن تستحق الاحتفاء</h2><p>نقاط من التقييمات الفعلية لطلاب المرحلة والصف المرتبطين بحسابك. تظهر الأسماء مختصرة حفاظًا على الخصوصية.</p></div></Panel>{loading?<Panel><p role="status">جارٍ تحميل النتائج…</p></Panel>:error?<Panel><Empty text="تعذر تحميل لوحة التميّز"/><Button onClick={()=>void load()}>إعادة المحاولة</Button></Panel>:rows.length?<div className="stars-list">{rows.map((s,i)=><Panel key={i}><span className="star-rank">{s.rank_number}</span><Avatar name={s.display_name}/><div><h3>{s.display_name}</h3><small>{s.program_id==='diploma'?'الدبلومة':'ثنائي اللغة'} • {s.class_name}</small><p>{s.evaluation_count} متابعة</p></div><strong>{s.points}<small> نقطة</small></strong></Panel>)}</div>:<Panel><Empty text="تبدأ لوحة التميّز مع أول تقييم محفوظ هذا الأسبوع"/></Panel>}</>}
export function SchoolNotifications(){const {db,user,navigate,notify}=useApp();const [read,setRead]=useState<string[]>([]);const [busy,setBusy]=useState('');const mark=async(id:string)=>{setBusy(id);const {error}=await supabase!.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id);setBusy('');if(error)notify('تعذر تحديث الإشعار');else setRead(s=>[...s,id])};return <><PageTitle title="الإشعارات" subtitle="ملخصات متابعة القرآن"/><Panel>{db.notifications.length?db.notifications.map(n=><div className="notification-row" key={n.id}><Bell/><div><h3>{n.title}</h3><p>{n.body}</p><small>{dateText(n.date)}</small></div><Button onClick={()=>navigate(['reader','homework','messages','certificates'].includes(n.page||'')?n.page!:'review')}>عرض المتابعة</Button>{!n.readBy.includes(user!.id)&&!read.includes(n.id)&&<Button disabled={busy===n.id} onClick={()=>void mark(n.id)}>تم الاطلاع</Button>}</div>):<Empty text="لا توجد إشعارات جديدة"/>}</Panel></>}
export function SchoolAccount(){const {user,logout}=useApp();return <><PageTitle title="الحساب"/><AccountPreferences/><Panel><div className="row"><Avatar name={user!.name} src={user?.avatar}/><div><h2>{user?.name}</h2><Badge>{user?.role==='parent'?'ولي أمر':user?.role==='teacher'?'معلم':user?.role==='admin'?'مدير المنصة':user?.role==='principal'?'مدير المدرسة':'مشرف'}</Badge></div></div><p>مقرأة غراس • مدارس غراس الأخلاق الأهلية</p><Button onClick={()=>void logout()}>تسجيل الخروج</Button></Panel></>}
