import {useEffect,useState} from 'react';
import {useApp,dateText} from '../services/store';
import {supabase} from '../services/supabase';
import {Avatar,Badge,Button,Empty,Field,Modal,PageTitle,Panel} from '../components/ui';
import {roleNames} from '../utils/domain.mjs';
import type {User} from '../types';
type Note={id:string;teacher_id:string;author_id:string;note_type:string;body:string;created_at:string};
const isLeadership=(role?:string)=>['admin','principal','supervisor'].includes(role||'');
const isAdmin=(role?:string)=>['admin','principal'].includes(role||'');
export function SchoolSupervision(){
 const {db,user,navigate,notify}=useApp();const teachers=db.users.filter(u=>['teacher','head_teacher','supervisor_teacher'].includes(u.remoteRole||u.role));
 const [teacher,setTeacher]=useState(teachers[0]?.id||'');const [type,setType]=useState('متابعة');const [body,setBody]=useState('');const [notes,setNotes]=useState<Note[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);const result=await supabase!.from('supervisor_notes').select('*').order('created_at',{ascending:false}).limit(100);setLoading(false);if(result.error)notify('تعذر تحميل الملاحظات');else setNotes(result.data||[])};
 useEffect(()=>{void load()},[]);
 const all=Object.values(db.evaluations);const today=all.filter(e=>new Date(e.createdAt).toLocaleDateString('en-CA',{timeZone:'Asia/Riyadh'})===new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Riyadh'}));
 const write=async()=>{if(!teacher||!body.trim())return;setSaving(true);const result=await supabase!.from('supervisor_notes').insert({teacher_id:teacher,author_id:user!.id,note_type:type,body:body.trim()});setSaving(false);if(result.error)notify('تعذر حفظ الملاحظة');else{setBody('');notify('تم حفظ الملاحظة وإشعار المعلم');void load()}};
 if(!isLeadership(user?.role))return <Empty text="هذه الصفحة للمشرف والمدير"/>;
 return <><PageTitle title={isAdmin(user?.role)?'مركز إدارة مقرأة غراس':'مركز الإشراف'} subtitle="متابعة المدرسة والمعلمين والشعب" action={<Button onClick={()=>navigate('reports')}>تقارير المدرسة</Button>}/><div className="leadership-stats"><Panel><small>الطلاب</small><h2>{new Set(db.students.map(s=>s.academicId)).size}</h2><p>{db.students.length} قيدًا في البرنامجين</p></Panel><Panel><small>الشعب</small><h2>{db.classes.length}</h2></Panel><Panel><small>متابعات اليوم</small><h2>{today.length}</h2></Panel><Panel><small>تسميعات بانتظار المراجعة</small><h2>{db.recitations.filter(r=>r.status==='pending').length}</h2><Button onClick={()=>navigate('reader')}>فتح التسجيلات</Button></Panel></div><div className="school-shortcuts"><button onClick={()=>navigate('classes')}>توزيع المعلمين والشعب ←</button><button onClick={()=>navigate('students')}>الطلاب والشعب ←</button><button onClick={()=>navigate('plans')}>إدارة المقررات ←</button>{isAdmin(user?.role)&&<><button onClick={()=>navigate('users')}>إدارة حسابات الموظفين ←</button><button onClick={()=>navigate('settings')}>إعدادات المدرسة ←</button></>}<button onClick={()=>navigate('audit')}>سجل العمليات ←</button></div><Panel><h2>متابعة المعلمين</h2><div className="table-scroll"><table><thead><tr><th>المعلم</th><th>الشعب</th><th>الطلاب</th><th>متابعات اليوم</th><th>آخر تقييم</th></tr></thead><tbody>{teachers.map(t=>{const evaluations=all.filter(e=>e.teacherId===t.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));return <tr key={t.id}><td>{t.name}<Badge>{roleNames[t.role]}</Badge></td><td>{t.classIds.length}</td><td>{db.students.filter(s=>t.classIds.includes(s.classId)).length}</td><td>{today.filter(e=>e.teacherId===t.id).length}</td><td>{evaluations[0]?dateText(evaluations[0].createdAt):'لا توجد متابعة مسجلة'}</td></tr>})}</tbody></table></div></Panel><div className="two-grid leadership-notes"><Panel><h2>ملاحظة إشرافية للمعلم</h2><form onSubmit={e=>{e.preventDefault();void write()}}><Field label="المعلم"><select value={teacher} onChange={e=>setTeacher(e.target.value)}>{teachers.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><Field label="نوع المتابعة"><select value={type} onChange={e=>setType(e.target.value)}>{['إشادة','توجيه','متابعة','إجراء مطلوب'].map(t=><option key={t}>{t}</option>)}</select></Field><Field label="الملاحظة"><textarea required maxLength={4000} rows={4} value={body} onChange={e=>setBody(e.target.value)}/></Field><Button variant="gold" disabled={saving||!body.trim()} type="submit">حفظ وإشعار المعلم</Button></form></Panel><Panel><h2>سجل الملاحظات</h2>{loading?<p>جارٍ التحميل…</p>:notes.length?notes.map(n=><div className="leadership-note" key={n.id}><Badge tone="gold">{n.note_type}</Badge><h3>{db.users.find(u=>u.id===n.teacher_id)?.name}</h3><p>{n.body}</p><small>{dateText(n.created_at)} • {db.users.find(u=>u.id===n.author_id)?.name}</small></div>):<Empty text="لا توجد ملاحظات إشرافية بعد"/>}</Panel></div></>;
}
export function SchoolAssignments(){
 const {db,user,refresh,notify}=useApp();const teachers=db.users.filter(u=>u.active&&['teacher','head_teacher','supervisor_teacher'].includes(u.remoteRole||u.role));const [teacherId,setTeacherId]=useState('');const [selected,setSelected]=useState<string[]>([]);const [saving,setSaving]=useState(false);const [program,setProgram]=useState('');const [newSection,setNewSection]=useState('');const [gradeClass,setGradeClass]=useState(db.classes[0]?.remoteId||'');
 const choose=(t:User)=>{setTeacherId(t.id);setSelected(db.classes.filter(c=>t.classIds.includes(c.id)).map(c=>c.remoteId!))};
 const save=async()=>{setSaving(true);try{const result=await supabase!.rpc('set_teacher_classes',{target_teacher:teacherId,selected_classes:selected});if(result.error)throw result.error;await refresh();setTeacherId('');notify('تم حفظ الشعب وتحديث قائمة المعلم')}catch{notify('تعذر حفظ توزيع الشعب')}finally{setSaving(false)}};
 const add=async()=>{const c=db.classes.find(c=>c.remoteId===gradeClass);if(!c||!newSection.trim())return;setSaving(true);try{const result=await supabase!.rpc('save_school_class',{program:c.program,stage_name:c.stage,grade_name:c.grade,section_name:newSection.trim()});if(result.error)throw result.error;await refresh();setNewSection('');notify('تم حفظ الشعبة')}catch{notify('تعذر إضافة الشعبة؛ راجع الصف والرقم')}finally{setSaving(false)}};
 if(!isLeadership(user?.role))return <Empty text="هذه الصفحة للمشرف والمدير"/>;
 return <><PageTitle title="إدارة المعلمين والشعب" subtitle="توزيع واضح للشعب وقوائم الطلاب"/><div className="staff-grid">{teachers.map(t=><Panel key={t.id}><div className="row"><Avatar name={t.name}/><h3>{t.name}</h3></div><p>{t.classIds.length} شعبة • {db.students.filter(s=>t.classIds.includes(s.classId)).length} طالبًا</p><div className="assignment-tags">{db.classes.filter(c=>t.classIds.includes(c.id)).map(c=><Badge key={c.id}>{c.name}</Badge>)}</div><Button variant="gold" onClick={()=>choose(t)}>تعديل الشعب</Button></Panel>)}</div><Panel className="leadership-notes"><h2>إضافة شعبة إلى صف موجود</h2><form className="toolbar" onSubmit={e=>{e.preventDefault();void add()}}><Field label="البرنامج والصف"><select value={gradeClass} onChange={e=>setGradeClass(e.target.value)}>{db.classes.filter((c,i,a)=>a.findIndex(x=>x.program===c.program&&x.stage===c.stage&&x.grade===c.grade)===i).map(c=><option key={c.id} value={c.remoteId}>{(c.program==='diploma'?'الدبلومة':'ثنائي اللغة')+' • '+c.stage+' • '+c.grade}</option>)}</select></Field><Field label="اسم أو رقم الشعبة"><input required maxLength={30} value={newSection} onChange={e=>setNewSection(e.target.value)}/></Field><Button type="submit" disabled={saving||!newSection.trim()}>حفظ الشعبة</Button></form></Panel>{teacherId&&<Modal title={'شعب '+teachers.find(t=>t.id===teacherId)?.name} onClose={()=>!saving&&setTeacherId('')}><Field label="عرض البرنامج"><select value={program} onChange={e=>setProgram(e.target.value)}><option value="">كل البرامج</option><option value="diploma">الدبلومة</option><option value="bilingual">ثنائي اللغة</option></select></Field><div className="setup-class-grid">{db.classes.filter(c=>!program||c.program===program).map(c=><label key={c.id}><input type="checkbox" disabled={saving} checked={selected.includes(c.remoteId!)} onChange={e=>setSelected(v=>e.target.checked?[...v,c.remoteId!]:v.filter(id=>id!==c.remoteId))}/><span><b>{c.name}</b><small>{db.students.filter(s=>s.classId===c.id).length} طالبًا</small></span></label>)}</div><div className="modal-actions"><p>{selected.length} شعبة مختارة</p><Button variant="gold" disabled={saving} onClick={()=>void save()}>{saving?'جارٍ الحفظ…':'حفظ التوزيع'}</Button></div></Modal>}</>;
}
type StaffDraft={id:string;name:string;role:string;active:boolean};
export function SchoolStaff(){
 const {db,user,refresh,notify}=useApp();const [draft,setDraft]=useState<StaffDraft|null>(null);const [saving,setSaving]=useState(false);const [created,setCreated]=useState<{name:string;access_code:string}|null>(null);
 const send=async()=>{if(!draft)return;setSaving(true);try{const result=await supabase!.functions.invoke('platform-administration',{body:{action:draft.id?'update':'create',...draft}});if(result.error){const context=(result.error as {context?:Response}).context;let message='تعذر حفظ الحساب';if(context){try{message=(await context.json()).error||message}catch{}}throw new Error(message);}if(result.data?.error)throw new Error(result.data.error);await refresh();if(result.data.access_code)setCreated({name:result.data.name,access_code:result.data.access_code});setDraft(null);notify('تم حفظ حساب الموظف')}catch(e){notify(e instanceof Error?e.message:'تعذر حفظ الحساب')}finally{setSaving(false)}};
 if(!isAdmin(user?.role))return <Empty text="إدارة الحسابات لمدير المنصة"/>;
 return <><PageTitle title="حسابات الموظفين" subtitle="إدارة الأسماء والأدوار وحالة الحساب" action={<Button variant="gold" onClick={()=>setDraft({id:'',name:'',role:'teacher',active:true})}>إضافة حساب موظف</Button>}/><Panel><div className="table-scroll"><table><thead><tr><th>الاسم</th><th>الدور</th><th>الحالة</th><th>الشعب</th><th>إدارة</th></tr></thead><tbody>{db.users.map(u=><tr key={u.id}><td>{u.name}</td><td>{roleNames[u.role]}</td><td><Badge tone={u.active?'green':'amber'}>{u.active?'نشط':'موقوف'}</Badge></td><td>{u.classIds.length}</td><td><Button onClick={()=>setDraft({id:u.id,name:u.name,role:u.remoteRole||u.role,active:u.active})}>تعديل الحساب</Button></td></tr>)}</tbody></table></div></Panel>{draft&&<Modal title={draft.id?'تعديل حساب الموظف':'حساب موظف جديد'} onClose={()=>!saving&&setDraft(null)}><form onSubmit={e=>{e.preventDefault();void send()}}><Field label="الاسم"><input required minLength={3} maxLength={150} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field><Field label="الدور"><select disabled={draft.id===user?.id} value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}><option value="teacher">معلم</option><option value="supervisor_teacher">مشرف ومعلم</option><option value="supervisor">مشرف</option><option value="admin">مدير المنصة</option></select></Field>{draft.id&&<label className="checkbox-label"><input type="checkbox" disabled={draft.id===user?.id} checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/>الحساب نشط</label>}<Button variant="gold" disabled={saving} type="submit">{saving?'جارٍ الحفظ…':'حفظ الحساب'}</Button></form></Modal>}{created&&<Modal title="تم إنشاء الحساب" onClose={()=>setCreated(null)}><h3>{created.name}</h3><Field label="رقم الدخول"><input readOnly value={created.access_code}/></Field><p>احفظ الرقم لتسليمه لصاحب الحساب.</p><Button onClick={()=>setCreated(null)}>تم</Button></Modal>}</>;
}
export function SchoolPlatformSettings(){
 const {db,user,refresh,notify}=useApp();const [school,setSchool]=useState(db.settings.school);const [term,setTerm]=useState(db.settings.term);const [year,setYear]=useState(db.settings.year);const [termStart,setTermStart]=useState(db.settings.termStartDate||'2026-08-23');const [saving,setSaving]=useState(false);
 const save=async()=>{setSaving(true);try{const result=await supabase!.from('platform_settings').update({school:school.trim(),term:term.trim(),year:year.trim(),term_start_date:termStart,updated_at:new Date().toISOString()}).eq('id',true).select('id');if(result.error||result.data?.length!==1)throw Error();await refresh();notify('تم حفظ إعدادات المدرسة')}catch{notify('تعذر حفظ الإعدادات')}finally{setSaving(false)}};
 if(!isAdmin(user?.role))return <Empty text="إعدادات المدرسة لمدير المنصة"/>;
 return <><PageTitle title="إعدادات مقرأة غراس" subtitle="الهوية المدرسية والفصل الدراسي"/><Panel><form onSubmit={e=>{e.preventDefault();void save()}}><img className="settings-logo" src={db.settings.logo} alt="شعار المدرسة"/><Field label="اسم المدرسة"><input required maxLength={150} value={school} onChange={e=>setSchool(e.target.value)}/></Field><Field label="الفصل الدراسي"><input required maxLength={100} value={term} onChange={e=>setTerm(e.target.value)}/></Field><Field label="العام الهجري"><input required maxLength={10} value={year} onChange={e=>setYear(e.target.value)}/></Field><Field label="بداية الأسبوع الدراسي الأول"><input required type="date" value={termStart} onChange={e=>setTermStart(e.target.value)}/></Field><Button variant="gold" disabled={saving} type="submit">حفظ الإعدادات</Button></form></Panel></>;
}
export function SchoolAudit(){
 const {db,user,notify}=useApp();const [rows,setRows]=useState<Array<{id:number;actor_id:string;action:string;entity_type:string;created_at:string}>>([]);const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);const result=await supabase!.from('audit_logs').select('id,actor_id,action,entity_type,created_at').order('created_at',{ascending:false}).limit(200);setLoading(false);if(result.error)notify('تعذر تحميل السجل');else setRows(result.data||[])};useEffect(()=>{void load()},[]);
 if(!isLeadership(user?.role))return <Empty text="سجل العمليات للإشراف والإدارة"/>;
 return <><PageTitle title="سجل العمليات" subtitle="آخر 200 عملية إدارية محفوظة" action={<Button onClick={()=>void load()}>تحديث</Button>}/><Panel>{loading?<p>جارٍ التحميل…</p>:rows.length?<div className="table-scroll"><table><thead><tr><th>الإجراء</th><th>المستخدم</th><th>التاريخ</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.action}</td><td>{db.users.find(u=>u.id===r.actor_id)?.name||'موظف المدرسة'}</td><td>{dateText(r.created_at)}</td></tr>)}</tbody></table></div>:<Empty text="لا توجد عمليات إدارية مسجلة"/>}</Panel></>;
}
export function SchoolRolePermissions(){return <><PageTitle title="صلاحيات الأدوار" subtitle="صلاحيات محفوظة في قاعدة المنصة"/><Panel><div className="table-scroll"><table><thead><tr><th>الأداة</th><th>مدير المنصة</th><th>المشرف</th><th>المعلم</th><th>ولي الأمر</th></tr></thead><tbody>{[['عرض الطلاب والمتابعة','جميع الطلاب','جميع الطلاب','شعبه فقط','أبناؤه فقط'],['التقييم ومراجعة التسميع','كل الشعب','كل الشعب','شعبه فقط','رفع التسميع'],['المقررات وتوزيع المعلمين','إدارة كاملة','إدارة كاملة','مقرر شعبه','عرض المطلوب'],['التقارير وسجل الإدارة','كامل','كامل','متابعة شعبه','ملخص أبنائه'],['الحسابات والأدوار والإعدادات','إدارة كاملة','غير متاح','غير متاح','غير متاح']].map(row=><tr key={row[0]}>{row.map((cell,i)=><td key={i}>{cell}</td>)}</tr>)}</tbody></table></div></Panel></>};
