import {useEffect,useState} from 'react';import {useApp,dateText} from '../services/store';import {supabase} from '../services/supabase';import {Badge,Button,Empty,Field,PageTitle,Panel} from '../components/ui';
type PrivateMessage={id:string;student_id:string;teacher_id:string;sender_id:string;sender_name:string;kind:string;body:string;created_at:string;was_read:boolean};type TeacherChoice={student_id:string;teacher_id:string;teacher_name:string};
export default function SchoolCommunication(){const {user,students,studentId,notify}=useApp();const family=user?.role==='parent';const [selectedStudent,setSelectedStudent]=useState(students.find(s=>s.id===studentId)?.remoteId||students[0]?.remoteId||'');const student=students.find(s=>s.remoteId===selectedStudent)||students[0];const [teacher,setTeacher]=useState('');const [messages,setMessages]=useState<PrivateMessage[]>([]);const [teachers,setTeachers]=useState<TeacherChoice[]>([]);const [body,setBody]=useState('');const [kind,setKind]=useState(family?'استفسار':'رسالة');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [search,setSearch]=useState('');
 const load=async()=>{const r=await supabase!.rpc('school_conversations');setLoading(false);if(r.error){setError('تعذر تحميل المحادثات');return}setMessages(r.data.messages||[]);setTeachers(r.data.teachers||[])};
 useEffect(()=>{void load()},[]);const choices=teachers.filter(t=>t.student_id===student?.remoteId);const teacherId=family?(choices.find(t=>t.teacher_id===teacher)?.teacher_id||choices[0]?.teacher_id||''):user!.id;const teacherName=choices.find(t=>t.teacher_id===teacherId)?.teacher_name||user?.name;
 const thread=messages.filter(m=>m.student_id===student?.remoteId&&m.teacher_id===teacherId&&(!search||m.body.includes(search))).sort((a,b)=>a.created_at.localeCompare(b.created_at));const unread=thread.filter(m=>m.sender_id!==user?.id&&!m.was_read);
 const mark=async()=>{if(!unread.length)return;const r=await supabase!.from('school_message_receipts').upsert(unread.map(m=>({message_id:m.id,user_id:user!.id})),{onConflict:'message_id,user_id',ignoreDuplicates:true});if(r.error)notify('تعذر حفظ حالة القراءة');else await load()};
 const send=async()=>{if(!student?.remoteId||!teacherId||!body.trim())return;setBusy(true);setError('');try{const r=await supabase!.from('school_private_messages').insert({student_id:student.remoteId,teacher_id:teacherId,sender_id:user!.id,kind,body:body.trim()});if(r.error)throw r.error;setBody('');await load();notify('تم إرسال الرسالة الخاصة وإشعار المستلم')}catch{setError('تعذر إرسال الرسالة. تحقق من ارتباط المعلم بالشعبة.')}finally{setBusy(false)}};
 const templates=family?['ما المطلوب مراجعته قبل التسميع القادم؟','تمت متابعة المقرر، ونرجو توجيهكم للخطوة القادمة.','هل يمكن توضيح ملاحظة التقييم؟']:['أحسنت يا '+(student?.name.split(' ')[0]||'طالبنا')+'، نعتز بجهدك في رحلة القرآن.','يرجى مراجعة المقرر المحدد قبل التسميع القادم.','يمكن إرسال تسميع صوتي من صفحة المقرأة.','نوصي بتقسيم المقرر إلى مقاطع قصيرة مع التكرار.','شكرًا للأسرة على المتابعة والتعاون.','يسعدنا تواصلكم بشأن أي صعوبة في المقرر.'];
 return <><PageTitle title="التواصل الخاص" subtitle={family?'محادثة مرتبطة بابنك مع معلمه':'رسائل مستقلة لكل طالب وولي أمره'} action={<Button onClick={()=>void load()}>تحديث</Button>}/><Panel><div className="toolbar"><Field label="الطالب والبرنامج"><select value={student?.remoteId||''} onChange={e=>{setSelectedStudent(e.target.value);setTeacher('');setSearch('');setBody('')}}>{students.map(s=><option key={s.id} value={s.remoteId}>{s.name} • {s.program==='diploma'?'الدبلومة':'ثنائي اللغة'}</option>)}</select></Field>{family&&<Field label="المعلم"><select value={teacherId} onChange={e=>{setTeacher(e.target.value);setBody('')}}>{choices.length?choices.map(t=><option key={t.teacher_id} value={t.teacher_id}>{t.teacher_name}</option>):<option value="">لم يُعيّن معلم لهذه الشعبة بعد</option>}</select></Field>}<Field label="البحث في المحادثة"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="كلمة في الرسائل"/></Field></div></Panel>{error&&<p className="form-alert" role="alert">{error}</p>}<div className="private-communication"><Panel className="private-thread"><div className="section-head"><div><h2>{student?.name||'اختر طالبًا'}</h2><small>{family?teacherName:'محادثتك مع ولي الأمر'} • أحدث الرسائل</small></div><Badge>{thread.length} رسالة</Badge></div>{unread.length>0&&<Button variant="gold" onClick={()=>void mark()}>تمت قراءة {unread.length} رسالة جديدة</Button>}<div className="private-thread-messages">{loading?<p role="status">جارٍ تحميل الرسائل…</p>:thread.length?thread.map(m=><article className={'private-bubble '+(m.sender_id===user?.id?'mine':'received')} key={m.id}><div><b>{m.sender_id===user?.id?'أنت':m.sender_id===m.teacher_id?m.sender_name:'ولي الأمر'}</b><Badge tone={m.kind==='إشادة'?'gold':''}>{m.kind}</Badge></div><p>{m.body}</p><small>{dateText(m.created_at)}{m.sender_id===user?.id?' • '+(m.was_read?'✓ تمت القراءة':'تم الإرسال'):''}</small></article>):<Empty text="لا توجد رسائل في هذه المحادثة"/>}</div></Panel><Panel className="private-composer"><h2>{family?'رسالة إلى المعلم':'رسالة إلى ولي الأمر'}</h2><Field label="نوع الرسالة"><select value={kind} onChange={e=>setKind(e.target.value)}>{(family?['رسالة','استفسار']:['رسالة','إشادة','تذكير','توجيه','استفسار']).map(t=><option key={t}>{t}</option>)}</select></Field><Field label="نص الرسالة"><textarea maxLength={4000} rows={7} value={body} onChange={e=>setBody(e.target.value)} placeholder="اكتب رسالتك الخاصة"/></Field><small>{body.length} / 4000</small><div className="message-templates">{templates.map(t=><button key={t} onClick={()=>{setBody(t);if(t.includes('أحسنت'))setKind('إشادة')}}>{t}</button>)}</div><Button variant="gold wide" disabled={busy||!body.trim()||!student||!teacherId} onClick={()=>void send()}>{busy?'جارٍ الإرسال…':'إرسال الرسالة الخاصة'}</Button></Panel></div></>
}
