import {useEffect,useMemo,useRef,useState} from 'react';
import {BookOpen,Bookmark,ChevronLeft,ChevronRight,Play,Pause,RotateCcw,Search,Eye,EyeOff,Maximize2,Minimize2,Volume2,Copy,Check,Timer,Settings2} from 'lucide-react';
import {useApp} from '../services/store';
import {supabase} from '../services/supabase';
import {quranSurahs,reciters} from '../data/quran';
import {Button,Field,Modal,Panel,Badge} from '../components/ui';
import {normalizeQuran,flattenQuran,clampRange,nextPractice} from '../utils/mushaf.mjs';
import {riyadhDate} from '../utils/school-calendar.mjs';
type Ayah={number:number;numberInSurah:number;text:string;juz:number;page:number;surah:number;surahName:string};
type QuranSurah={number:number;name:string;ayahs:Ayah[]};
type Preferences={surah:number;page:number;mode:string;reciter:string;font:number;theme:string;bookmarks:number[];last:number;note:string};
let cached:Promise<QuranSurah[]>|null=null;
const defaults:Preferences={surah:1,page:1,mode:'page',reciter:'ar.husary',font:30,theme:'paper',bookmarks:[],last:1,note:''};
export default function TeacherMushaf(){
 const {user,db,students,notify,refresh}=useApp();const family=user?.role==='parent'||user?.role==='student';const key='gheras-mushaf-v2-'+user?.id;
 const [prefs,setPrefs]=useState<Preferences>(()=>{try{const v=JSON.parse(localStorage.getItem(key)||'{}');return {...defaults,...v,bookmarks:Array.isArray(v.bookmarks)?v.bookmarks.filter((n:number)=>n>=1&&n<=6236):[]}}catch{return defaults}});
 const [data,setData]=useState<QuranSurah[]>([]);const [loading,setLoading]=useState(true);const [dataError,setDataError]=useState('');const [retry,setRetry]=useState(0);
 const [query,setQuery]=useState('');const [searchScope,setSearchScope]=useState('surahs');const [showIndex,setShowIndex]=useState(false);const [selected,setSelected]=useState(Math.max(1,Math.min(6236,prefs.last)));const [juz,setJuz]=useState(1);
 const [from,setFrom]=useState(1);const [to,setTo]=useState(7);const [verseRepeat,setVerseRepeat]=useState(3);const [rangeRepeat,setRangeRepeat]=useState(1);const [gap,setGap]=useState(1);const [speed,setSpeed]=useState(1);const [volume,setVolume]=useState(.8);const [continuous,setContinuous]=useState(false);
 const [playing,setPlaying]=useState(false);const [audioError,setAudioError]=useState('');const [conceal,setConceal]=useState(false);const [revealed,setRevealed]=useState<number[]>([]);const [presentation,setPresentation]=useState(false);
 const [cycles,setCycles]=useState({verseCount:1,rangeCount:1});const [sessionSeconds,setSessionSeconds]=useState(0);const [sessionOn,setSessionOn]=useState(false);
 const [homework,setHomework]=useState(false);const classes=db.classes.filter(c=>students.some(s=>s.classId===c.id));const [targetClass,setTargetClass]=useState(classes[0]?.remoteId||'');const [targetStudent,setTargetStudent]=useState('');const [due,setDue]=useState(riyadhDate());const [kind,setKind]=useState('حفظ');const [instructions,setInstructions]=useState('');const [publishing,setPublishing]=useState(false);
 const audio=useRef<HTMLAudioElement>(null);const root=useRef<HTMLDivElement>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const practice=useRef(false);const counts=useRef({verseCount:1,rangeCount:1});const playIntent=useRef(false);
 const all=useMemo(()=>flattenQuran(data) as Ayah[],[data]);const ayah=all[selected-1];const surah=data[prefs.surah-1];const range=clampRange(from,to,surah?.ayahs.length||7);
 const update=(v:Partial<Preferences>)=>setPrefs(p=>({...p,...v}));
 useEffect(()=>{localStorage.setItem(key,JSON.stringify(prefs))},[prefs,key]);
 useEffect(()=>{let active=true;setLoading(true);setDataError('');if(!cached)cached=fetch(import.meta.env.BASE_URL+'quran-uthmani.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(q=>{if(q.data.surahs.length!==114||q.data.surahs.reduce((n:number,s:QuranSurah)=>n+s.ayahs.length,0)!==6236)throw Error();return q.data.surahs}).catch(e=>{cached=null;throw e});cached.then(q=>{if(active){setData(q);setJuz(q.flatMap(s=>s.ayahs)[selected-1]?.juz||1);setLoading(false)}}).catch(()=>{if(active){setDataError('تعذر تحميل المصحف. تحقق من الاتصال وأعد المحاولة.');setLoading(false)}});return()=>{active=false}},[retry]);
 useEffect(()=>{setFrom(1);setTo(Math.min(7,surah?.ayahs.length||7));setRevealed([])},[prefs.surah,surah?.ayahs.length]);
 useEffect(()=>{if(!sessionOn)return;const id=setInterval(()=>setSessionSeconds(n=>n+1),1000);return()=>clearInterval(id)},[sessionOn]);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);audio.current?.pause()},[]);
 useEffect(()=>{const handler=()=>setPresentation(Boolean(document.fullscreenElement));document.addEventListener('fullscreenchange',handler);return()=>document.removeEventListener('fullscreenchange',handler)},[]);
 const stop=()=>{playIntent.current=false;practice.current=false;if(timer.current)clearTimeout(timer.current);timer.current=null;audio.current?.pause();setPlaying(false)};
 const playAudio=()=>{setAudioError('');if(audio.current){audio.current.playbackRate=speed;audio.current.volume=volume;void audio.current.play().catch(()=>{playIntent.current=false;setPlaying(false);setAudioError('تعذر تشغيل الصوت؛ يمكنك متابعة القراءة أو تجربة قارئ آخر.')})}};
 const start=(number:number)=>{if(timer.current)clearTimeout(timer.current);timer.current=null;playIntent.current=true;setAudioError('');if(number===selected)playAudio();else setSelected(number)};
 useEffect(()=>{if(playIntent.current)playAudio()},[selected,prefs.reciter]);
 useEffect(()=>{if(audio.current){audio.current.playbackRate=speed;audio.current.volume=volume}},[speed,volume]);
 const go=(a:Ayah)=>{stop();setSelected(a.number);update({last:a.number,surah:a.surah,page:a.page});setJuz(a.juz);setShowIndex(false)};
 const visible=useMemo(()=>prefs.mode==='surah'?(surah?.ayahs||[]).map(a=>({...a,surah:prefs.surah,surahName:surah?.name||''})):prefs.mode==='juz'?all.filter(a=>a.juz===juz&&a.page===prefs.page):all.filter(a=>a.page===prefs.page),[all,surah,prefs.mode,prefs.page,prefs.surah,juz]);
 const matches=useMemo(()=>{const q=normalizeQuran(query);if(!q)return [];return all.filter(a=>normalizeQuran(a.text).includes(q)).slice(0,80)},[all,query]);
 const surahs=quranSurahs.filter(s=>!query||normalizeQuran(s.name).includes(normalizeQuran(query))||s.english.toLowerCase().includes(query.toLowerCase())||String(s.id)===query);
 const beginPractice=()=>{if(!surah)return;stop();counts.current={verseCount:1,rangeCount:1};setCycles(counts.current);practice.current=true;setSessionOn(true);update({mode:'surah'});start(surah.ayahs[range.from-1].number)};
 const ended=()=>{if(!ayah)return;if(practice.current){const next=nextPractice(ayah.numberInSurah,range.from,range.to,counts.current.verseCount,verseRepeat,counts.current.rangeCount,rangeRepeat);counts.current={verseCount:next.verseCount,rangeCount:next.rangeCount};setCycles(counts.current);if(next.done){stop();notify('اكتمل تكرار المقطع المحدد');return}timer.current=setTimeout(()=>start(surah!.ayahs[next.index-1].number),gap*1000)}else if(continuous&&selected<6236){const n=all[selected];update({page:n.page,surah:n.surah,last:n.number});setJuz(n.juz);timer.current=setTimeout(()=>start(n.number),gap*1000)}else stop()};
 const chooseSurah=(id:number)=>{const first=all.find(a=>a.surah===id);if(first)go(first);update({mode:'surah',surah:id})};
 const choosePage=(p:number)=>{const n=Math.max(1,Math.min(604,p));const first=all.find(a=>a.page===n);if(first)go(first);update({page:n,mode:prefs.mode==='juz'?'juz':'page'})};
 const bookmark=(n:number)=>update({bookmarks:prefs.bookmarks.includes(n)?prefs.bookmarks.filter(x=>x!==n):[...prefs.bookmarks,n]});
 const fullscreen=async()=>{if(document.fullscreenElement){await document.exitFullscreen();return}if(presentation){setPresentation(false);return}try{await root.current?.requestFullscreen();setPresentation(true)}catch{setPresentation(v=>!v)}};
 const copy=async()=>{if(!ayah)return;try{await navigator.clipboard.writeText(ayah.text+' ﴿'+ayah.numberInSurah+'﴾ — '+ayah.surahName);notify('تم نسخ الآية ومرجعها')}catch{notify('تعذر النسخ على هذا الجهاز')}};
 const publish=async()=>{if(!surah||!user||!targetClass)return;setPublishing(true);try{const title='سورة '+quranSurahs[prefs.surah-1].name+' • الآيات '+range.from+'–'+range.to;const r=await supabase!.from('quran_homework').insert({teacher_id:user.id,class_id:targetClass,student_id:targetStudent||null,kind,title,instructions:instructions.trim(),due_date:due});if(r.error)throw r.error;await refresh();setHomework(false);notify('تم نشر مقرر المصحف وإشعار الأسرة')}catch{notify('تعذر نشر المقرر')}finally{setPublishing(false)}};
 const source=ayah?'https://cdn.islamic.network/quran/audio/128/'+prefs.reciter+'/'+ayah.number+'.mp3':'';
 return <div ref={root} className={'quran-studio theme-'+prefs.theme+(presentation?' presentation':'')} dir="rtl">
 <div className="studio-top"><div><span className="studio-kicker">{family?'رحلتك مع القرآن':'مصحف المعلم'}</span><h2>المصحف الكريم</h2><small>114 سورة • 30 جزءًا • 604 صفحات</small></div><div className="studio-actions"><Button onClick={()=>setShowIndex(v=>!v)}><Search size={16}/>الفهرس والبحث</Button><Button onClick={()=>void fullscreen()}>{presentation?<Minimize2 size={16}/>:<Maximize2 size={16}/>}وضع العرض</Button></div></div>
 <div className="studio-navigation"><Field label="السورة"><select value={prefs.surah} onChange={e=>chooseSurah(Number(e.target.value))}>{quranSurahs.map(s=><option value={s.id} key={s.id}>{s.id}. {s.name}</option>)}</select></Field><Field label="طريقة القراءة"><select value={prefs.mode} onChange={e=>update({mode:e.target.value})}><option value="page">صفحات المصحف</option><option value="surah">السورة كاملة</option><option value="juz">أجزاء المصحف</option></select></Field><Field label="الصفحة"><input type="number" min={1} max={604} value={prefs.page} onChange={e=>choosePage(Number(e.target.value))}/></Field><Field label="الجزء"><select value={juz} onChange={e=>{const n=Number(e.target.value);const a=all.find(a=>a.juz===n);if(a)go(a);setJuz(n);update({mode:'juz'})}}>{Array.from({length:30},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></Field></div>
 {showIndex&&<Panel className="studio-index"><div className="toolbar"><Field label="البحث في المصحف"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="اسم سورة أو كلمة من آية"/></Field><Field label="نطاق البحث"><select value={searchScope} onChange={e=>setSearchScope(e.target.value)}><option value="surahs">فهرس السور</option><option value="ayahs">نص الآيات</option><option value="bookmarks">علاماتي المحفوظة</option></select></Field></div><div className="studio-results">{searchScope==='surahs'?surahs.map(s=><button key={s.id} onClick={()=>chooseSurah(s.id)}><b>{s.id} • {s.name}</b><small>{s.ayahs} آية</small><ChevronLeft size={15}/></button>):(searchScope==='bookmarks'?all.filter(a=>prefs.bookmarks.includes(a.number)):matches).map(a=><button key={a.number} onClick={()=>go(a)}><span>{a.text}</span><small>{a.surahName} • الآية {a.numberInSurah} • الصفحة {a.page}</small></button>)}{searchScope==='ayahs'&&query&&matches.length===0&&<p>لا توجد نتائج لهذه الكلمة.</p>}{searchScope==='ayahs'&&!query&&<p>اكتب كلمة للبحث في جميع آيات المصحف.</p>}{searchScope==='ayahs'&&matches.length===80&&<p>تظهر أول 80 نتيجة؛ أضف كلمة لتحديد البحث.</p>}{searchScope==='bookmarks'&&!prefs.bookmarks.length&&<p>اضغط علامة الحفظ عند الآية لإضافتها هنا.</p>}</div></Panel>}
 <div className="studio-body"><div className="studio-book-area">
 <div className="studio-book" style={{'--verse-size':prefs.font+'px'} as React.CSSProperties}><div className="book-spine" aria-hidden="true"/><header className="book-page-header"><span>{prefs.mode==='surah'?'سورة '+quranSurahs[prefs.surah-1].name:'الصفحة '+prefs.page}</span><BookOpen size={20}/><span>الجزء {visible[0]?.juz||juz}</span></header>
 {loading?<p role="status" className="studio-loading">جارٍ فتح المصحف…</p>:dataError?<div role="alert"><p>{dataError}</p><Button onClick={()=>setRetry(n=>n+1)}>إعادة المحاولة</Button></div>:<div className="studio-verses">{visible.map(a=><div className={'studio-verse '+(selected===a.number?'selected':'')+(prefs.mode==='surah'&&a.numberInSurah>=range.from&&a.numberInSurah<=range.to?' practice-range':'')} key={a.number}>
 {(a.numberInSurah===1||a.number===visible[0]?.number)&&<div className="book-surah-title">سورة {quranSurahs[a.surah-1].name}</div>}
 <button className="verse-reading" aria-label={'سورة '+quranSurahs[a.surah-1].name+' الآية '+a.numberInSurah} onClick={()=>{setSelected(a.number);update({last:a.number,surah:a.surah});setJuz(a.juz);if(conceal)setRevealed(v=>v.includes(a.number)?v.filter(n=>n!==a.number):[...v,a.number])}}>
 <span className="uthmani-text">{conceal&&!revealed.includes(a.number)?'••• اضغط لكشف الآية •••':a.text}</span><span className="verse-medallion">{a.numberInSurah}</span></button><div className="verse-actions"><button aria-label={'تشغيل الآية '+a.numberInSurah} onClick={()=>{stop();start(a.number)}}><Play size={14}/></button><button aria-label={'حفظ علامة الآية '+a.numberInSurah} aria-pressed={prefs.bookmarks.includes(a.number)} onClick={()=>bookmark(a.number)}><Bookmark size={14} fill={prefs.bookmarks.includes(a.number)?'currentColor':'none'}/></button><small>{quranSurahs[a.surah-1].name} • {a.numberInSurah}</small></div></div>)}</div>}
 <footer className="book-page-footer"><Button disabled={prefs.mode==='surah'?prefs.surah<=1:prefs.page<=1} onClick={()=>prefs.mode==='surah'?chooseSurah(prefs.surah-1):choosePage(prefs.page-1)}><ChevronRight size={16}/>السابق</Button><span>{prefs.mode==='surah'?prefs.surah+' / 114':prefs.page+' / 604'}</span><Button disabled={prefs.mode==='surah'?prefs.surah>=114:prefs.page>=604} onClick={()=>prefs.mode==='surah'?chooseSurah(prefs.surah+1):choosePage(prefs.page+1)}>التالي<ChevronLeft size={16}/></Button></footer></div>
 <div className="studio-playbar"><Button disabled={!ayah} variant="gold" onClick={()=>playing?stop():start(selected)}>{playing?<Pause size={18}/>:<Play size={18}/>} {playing?'إيقاف مؤقت':'استماع'}</Button><div><b>{ayah?quranSurahs[ayah.surah-1].name+' • الآية '+ayah.numberInSurah:'اختر آية'}</b><small>{reciters.find(r=>r.id===prefs.reciter)?.name}</small></div><Button disabled={selected<=1} onClick={()=>{stop();if(all[selected-2])go(all[selected-2])}}>الآية السابقة</Button><Button disabled={selected>=6236||!ayah} onClick={()=>{stop();if(all[selected])go(all[selected])}}>الآية التالية</Button><Button disabled={!ayah} onClick={()=>void copy()}><Copy size={15}/>نسخ الآية</Button><audio ref={audio} src={source} preload="none" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={ended} onError={()=>{setPlaying(false);setAudioError('الصوت غير متاح الآن. جرّب قارئًا آخر أو أعد التشغيل.')}}/></div>{audioError&&<p className="studio-audio-error" role="alert">{audioError}<Button onClick={()=>start(selected)}>إعادة تشغيل الصوت</Button></p>}
 </div><aside className="studio-tools">
 <Panel><h3><RotateCcw size={18}/>مقطع الحفظ</h3><div className="two-grid"><Field label="من الآية"><input type="number" min={1} max={surah?.ayahs.length||7} value={range.from} onChange={e=>{stop();setFrom(Number(e.target.value))}}/></Field><Field label="إلى الآية"><input type="number" min={range.from} max={surah?.ayahs.length||7} value={range.to} onChange={e=>{stop();setTo(Number(e.target.value))}}/></Field><Field label="تكرار كل آية"><select value={verseRepeat} onChange={e=>{stop();setVerseRepeat(Number(e.target.value))}}>{[1,2,3,5,7,10].map(n=><option key={n}>{n}</option>)}</select></Field><Field label="تكرار المقطع"><select value={rangeRepeat} onChange={e=>{stop();setRangeRepeat(Number(e.target.value))}}>{[1,2,3,5,10].map(n=><option key={n}>{n}</option>)}</select></Field></div><Field label="مهلة الترديد بين الآيات"><select value={gap} onChange={e=>setGap(Number(e.target.value))}>{[0,1,2,3,5,10].map(n=><option key={n} value={n}>{n} ثانية</option>)}</select></Field><Button variant="gold wide" disabled={loading||!surah} onClick={beginPractice}><Play size={16}/>ابدأ تكرار المقطع</Button><small className="studio-cycle">تكرار الآية {cycles.verseCount} / {verseRepeat} • المقطع {cycles.rangeCount} / {rangeRepeat}</small><Button className="wide" onClick={()=>{stop();setConceal(v=>!v);setRevealed([])}}>{conceal?<Eye size={16}/>:<EyeOff size={16}/>} {conceal?'إظهار نص الآيات':'اختبار الحفظ بإخفاء الآيات'}</Button>{conceal&&<Button onClick={()=>setRevealed([])}>إخفاء الآيات المكشوفة مجددًا</Button>}{!family&&<Button className="wide" disabled={!surah||!classes.length} onClick={()=>{setInstructions('راجع سورة '+quranSurahs[prefs.surah-1].name+' من الآية '+range.from+' إلى '+range.to+'، مع تكرار كل آية '+verseRepeat+' مرات، ثم أرسل التسميع.');setHomework(true)}}>إسناد المقطع واجبًا</Button>}</Panel>
 <details className="studio-details" open><summary><Volume2 size={17}/>التلاوة والصوت</summary><Field label="القارئ"><select value={prefs.reciter} onChange={e=>update({reciter:e.target.value})}>{reciters.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field><Field label="سرعة التشغيل"><select value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[.5,.75,1,1.25,1.5].map(n=><option key={n} value={n}>{n}×</option>)}</select></Field><Field label="مستوى الصوت"><input type="range" min={0} max={1} step={.1} value={volume} onChange={e=>setVolume(Number(e.target.value))}/></Field><label className="studio-check"><input type="checkbox" checked={continuous} onChange={e=>setContinuous(e.target.checked)}/>استماع متواصل بعد الآية المختارة</label></details>
 <details className="studio-details"><summary><Settings2 size={17}/>راحة القراءة</summary><Field label="حجم خط الآيات"><input type="range" min={22} max={48} step={2} value={prefs.font} onChange={e=>update({font:Number(e.target.value)})}/></Field><Field label="لون صفحات المصحف"><select value={prefs.theme} onChange={e=>update({theme:e.target.value})}><option value="paper">ورق عاجي</option><option value="white">أبيض واضح</option><option value="night">قراءة ليلية</option></select></Field><Button onClick={()=>{const a=all[prefs.last-1];if(a)go(a)}}>العودة إلى آخر موضع قراءة</Button></details>
 <details className="studio-details"><summary><Timer size={17}/>جلسة التحفيظ</summary><p className="session-clock">{Math.floor(sessionSeconds/60).toString().padStart(2,'0')}:{(sessionSeconds%60).toString().padStart(2,'0')}</p><div className="row-actions"><Button onClick={()=>setSessionOn(v=>!v)}>{sessionOn?'إيقاف المؤقت':'ابدأ الجلسة'}</Button><Button onClick={()=>{setSessionOn(false);setSessionSeconds(0)}}>تصفير</Button></div><Field label="ملاحظة جلستك"><textarea rows={3} maxLength={2000} value={prefs.note} onChange={e=>update({note:e.target.value})}/></Field><small>الموضع والعلامات والملاحظة محفوظة لحسابك على هذا الجهاز.</small></details>
 </aside></div>
 {homework&&<Modal title="إسناد مقرر من المصحف" onClose={()=>!publishing&&setHomework(false)}><h3>سورة {quranSurahs[prefs.surah-1].name} • الآيات {range.from}–{range.to}</h3><Field label="الشعبة"><select value={targetClass} onChange={e=>{setTargetClass(e.target.value);setTargetStudent('')}}>{classes.map(c=><option value={c.remoteId} key={c.id}>{c.name}</option>)}</select></Field><Field label="المستفيد"><select value={targetStudent} onChange={e=>setTargetStudent(e.target.value)}><option value="">جميع طلاب الشعبة</option>{students.filter(s=>s.classId===classes.find(c=>c.remoteId===targetClass)?.id).map(s=><option key={s.id} value={s.remoteId}>{s.name}</option>)}</select></Field><Field label="نوع المقرر"><select value={kind} onChange={e=>setKind(e.target.value)}>{['حفظ','تلاوة','مراجعة','تثبيت','استماع','مقرأة'].map(k=><option key={k}>{k}</option>)}</select></Field><Field label="موعد المتابعة"><input type="date" required value={due} onChange={e=>setDue(e.target.value)}/></Field><Field label="إرشادات الأسرة"><textarea rows={3} maxLength={2000} value={instructions} onChange={e=>setInstructions(e.target.value)}/></Field><Button disabled={publishing||!due||!targetClass} variant="gold" onClick={()=>void publish()}>{publishing?'جارٍ النشر…':'نشر الواجب وإشعار الأسرة'}</Button></Modal>}
 </div>
}
