import {useState} from 'react';
import {supabase} from '../services/supabase';
import {manageTeacher} from '../services/teacher-management';
import {parseStudentBatch,studentBatchConflict,type StudentBatchRow} from '../utils/bulk-students.mjs';
import {Button,Field,Modal,Badge} from './ui';
import {saveStudentFile} from './StudentExports';
type Classroom={id:string;program_id:string;name:string;stage:string;active:boolean};
type Student={national_id:string;program_id:string;full_name:string;class_id:string};
export default function BulkStudents({classes,students,onClose,onSaved}:{classes:Classroom[];students:Student[];onClose:()=>void;onSaved:()=>Promise<void>}){
 const [classId,setClassId]=useState(classes.find(c=>c.active)?.id||'');const [text,setText]=useState('');const [rows,setRows]=useState<StudentBatchRow[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [results,setResults]=useState<Record<number,string>>({});
 const classroom=classes.find(c=>c.id===classId);const checked=rows.map(r=>({...r,error:r.error||(results[r.line]?'':classroom?studentBatchConflict(r,students,classroom):'اختر شعبة')}));
 const preview=()=>{setError('');setResults({});try{setRows(parseStudentBatch(text))}catch(e){setError(e instanceof Error?e.message:'تعذر قراءة القائمة');setRows([])}};
 const readFile=async(file?:File)=>{if(!file)return;if(file.size>2*1024*1024){setError('الحد الأقصى لملف القائمة 2 ميغابايت');return}const bytes=await file.arrayBuffer();let content=new TextDecoder('utf-8').decode(bytes);if(content.includes('\uFFFD'))content=new TextDecoder('windows-1256').decode(bytes);setText(content);setRows([]);setResults({});setError('')};
 const save=async()=>{if(!classroom||!rows.length||checked.some(r=>r.error))return;setBusy(true);setError('');try{
  const fresh=await supabase!.rpc('teacher_workspace');if(fresh.error)throw Error('تعذر التحقق من القائمة الحالية؛ لم تبدأ الإضافة');let current:Student[]=fresh.data.students;
  for(const row of rows){if(results[row.line]==='تمت الإضافة'||results[row.line]==='موجود بالفعل')continue;
   const conflict=studentBatchConflict(row,current,classroom);if(conflict){const same=current.find(s=>s.class_id===classId&&s.full_name.trim()===row.name&&(!row.number||s.national_id===row.number));if(same){setResults(r=>({...r,[row.line]:'موجود بالفعل'}));continue}throw Error('الطالب '+row.name+': '+conflict)}
   setResults(r=>({...r,[row.line]:'جارٍ الحفظ'}));
   try{await manageTeacher('student_save',{id:'',name:row.name,national_id:row.number,class_id:classId,login_is_temporary:!row.number});setResults(r=>({...r,[row.line]:'تمت الإضافة'}));current=[...current,{full_name:row.name,national_id:row.number,program_id:classroom.program_id,class_id:classId}]}catch(e){setResults(r=>({...r,[row.line]:'يحتاج مراجعة'}));throw e}
  }
 }catch(e){setError((e instanceof Error?e.message:'توقف الاتصال')+'؛ المحفوظ باقٍ. حدّث القائمة قبل إعادة المعاينة، ولا تعد إضافة الصفوف الناجحة.')}finally{await onSaved().catch(()=>setError('أعد تحديث قائمة الطلاب للتحقق من نتائج الدفعة'));setBusy(false)}};
 return <Modal title="إضافة الطلاب دفعة واحدة" onClose={()=>!busy&&onClose()}><p>اختر الشعبة، ثم الصق عمودي الاسم والرقم من Excel أو حمّل ملف CSV. الاسم والرقم فقط؛ الرقم الفارغ يُولّد له رقم مؤقت.</p><Field label="شعبة الدفعة"><select disabled={busy} value={classId} onChange={e=>{setClassId(e.target.value);setRows([]);setResults({})}}>{classes.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.program_id==='diploma'?'الدبلومة':'ثنائي اللغة'} • {c.stage} • {c.name.replace(/\s*-\s*غير موزع/g, '')}</option>)}</select></Field><Button disabled={busy} onClick={()=>saveStudentFile('\uFEFFالاسم,الرقم\r\n','قالب إضافة الطلاب.csv','text/csv;charset=utf-8')}>تنزيل القالب</Button><Field label="ملف CSV"><input disabled={busy} type="file" accept=".csv,.tsv,.txt" onChange={e=>void readFile(e.target.files?.[0])}/></Field><Field label="الأسماء والأرقام"><textarea disabled={busy} rows={6} value={text} onChange={e=>{setText(e.target.value);setRows([]);setResults({})}} placeholder="الاسم ثم الرقم، طالب في كل سطر"/></Field><Button disabled={busy||!text.trim()} onClick={preview}>معاينة وفحص الدفعة</Button>{error&&<p role="alert" className="form-alert">{error}</p>}{rows.length>0&&<><p>{rows.length} طالبًا • {checked.filter(r=>r.error).length} صفوف تحتاج تصحيحًا</p><div className="table-scroll" style={{maxHeight:280}}><table><thead><tr><th>م</th><th>الاسم</th><th>الرقم</th><th>الحالة</th></tr></thead><tbody>{checked.map(r=><tr key={r.line}><td>{r.line}</td><td>{r.name}</td><td dir="ltr">{r.number||'رقم مؤقت تلقائي'}</td><td><Badge tone={r.error?'amber':results[r.line]==='تمت الإضافة'?'green':''}>{results[r.line]||r.error||'جاهز للإضافة'}</Badge></td></tr>)}</tbody></table></div><p>يحفظ كل طالب منفصلًا ويُنشئ دخوله. إذا توقف الاتصال، يبقى الطلاب الناجحون محفوظين وتظهر حالة كل صف.</p><Button variant="gold" disabled={busy||checked.some(r=>r.error)||rows.every(r=>results[r.line]==='تمت الإضافة'||results[r.line]==='موجود بالفعل')} onClick={()=>void save()}>{busy?'جارٍ إضافة الطلاب…':'تأكيد إضافة الدفعة'}</Button></>}</Modal>;
}
