import {useState} from 'react';import {useApp} from '../services/store';import {supabase} from '../services/supabase';
import {scopedMessageStudents,familyMessageBatch} from '../utils/family-message-batch.mjs';import {Button,Field,Panel,Modal} from './ui';
export default function BulkFamilyMessage({onSent}:{onSent?:()=>Promise<void>}={}){
 const {db,students,user,notify}=useApp();const [program,setProgram]=useState('');const [grade,setGrade]=useState('');const [classIds,setClassIds]=useState<string[]>([]);const [kind,setKind]=useState('رسالة');const [body,setBody]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const [preview,setPreview]=useState<{groups:typeof students[];body:string;kind:string;id:string}|null>(null);
 const classes=db.classes.filter(c=>(!program||c.program===program)&&(!grade||c.stage+'|'+c.grade===grade));const grades=[...new Set(db.classes.filter(c=>!program||c.program===program).map(c=>c.stage+'|'+c.grade))];
 const groups=scopedMessageStudents(students,db.classes,{program,grade,classIds});
 const send=async()=>{if(!preview||!user||!supabase)return;setBusy(true);setError('');try{const payload=await familyMessageBatch(preview.groups,user.id,preview.body,preview.kind,preview.id);const r=await supabase.from('school_private_messages').upsert(payload,{onConflict:'id',ignoreDuplicates:true}).select('id');if(r.error)throw r.error;notify('تم إرسال '+(r.data?.length||0)+' رسالة خاصة للأهالي');setPreview(null);setBody('');void onSent?.()}catch{setError('تعذر تأكيد إرسال الدفعة. أعد المحاولة من هذه المعاينة؛ الرسالة نفسها لن تتكرر.')}finally{setBusy(false)}};
 if(user?.role==='parent')return null;
 return <Panel><h2>رسالة جماعية حسب الصف والشعب</h2><p>تصل رسالة خاصة لكل أسرة، ولا تظهر قائمة المستلمين للأهالي.</p><div className="toolbar"><Field label="مسار مستلمي الرسالة"><select value={program} onChange={e=>{setProgram(e.target.value);setGrade('');setClassIds([])}}><option value="">كل المسارات المتاحة</option><option value="diploma">الدبلومة</option><option value="bilingual">ثنائي اللغة</option></select></Field><Field label="صف مستلمي الرسالة"><select value={grade} onChange={e=>{setGrade(e.target.value);setClassIds([])}}><option value="">كل الصفوف المتاحة</option>{grades.map(g=><option key={g} value={g}>{g.replace('|',' • ')}</option>)}</select></Field><Field label="نوع الرسالة الجماعية"><select value={kind} onChange={e=>setKind(e.target.value)}>{['رسالة','إشادة','تذكير','توجيه','استفسار'].map(k=><option key={k}>{k}</option>)}</select></Field></div><details><summary>تحديد شعب بعينها ({classIds.length||'الكل'})</summary><p>دون تحديد شعب، تشمل الدفعة جميع الشعب المطابقة للمسار والصف أعلاه.</p>{classes.map(c=><label className="check-label" key={c.id}><input type="checkbox" checked={classIds.includes(c.remoteId||'')} onChange={e=>setClassIds(v=>e.target.checked?[...v,c.remoteId!]:v.filter(id=>id!==c.remoteId))}/>{c.name}</label>)}<Button onClick={()=>setClassIds([])}>اختيار جميع الشعب المطابقة</Button></details><Field label="نص الرسالة الجماعية"><textarea rows={4} maxLength={4000} value={body} onChange={e=>setBody(e.target.value)}/></Field><p>{groups.length} طالبًا مستهدفًا • {body.length} / 4000 حرف</p><Button variant="gold" disabled={!groups.length||!body.trim()} onClick={()=>{setError('');setPreview({groups,body:body.trim(),kind,id:crypto.randomUUID()})}}>معاينة المستلمين والإرسال</Button>{preview&&<Modal title="معاينة الرسالة الجماعية" onClose={()=>!busy&&setPreview(null)}><p>رسائل خاصة إلى {preview.groups.length} أسرة • {preview.kind}</p><p style={{whiteSpace:'pre-wrap'}}>{preview.body}</p><details><summary>أسماء الطلاب المستهدفين</summary><p>{preview.groups.map(g=>g[0].name).join('، ')}</p></details>{error&&<p role="alert">{error}</p>}<Button disabled={busy} variant="gold" onClick={()=>void send()}>{busy?'جارٍ الإرسال…':'تأكيد إرسال الرسالة للمستلمين'}</Button><Button disabled={busy} onClick={()=>setPreview(null)}>إلغاء</Button></Modal>}</Panel>;
}

