import {useEffect,useState} from 'react';
import {useApp} from '../services/store';
import {supabase} from '../services/supabase';
import {evaluationDate} from '../utils/report-period.mjs';
import {Button,Field,Modal} from './ui';
import {saveStudentFile} from './StudentExports';
import {studentReportDocument,type ExportStudent} from '../utils/student-export.mjs';
export default function StudentReport({student,studentId,onClose}:{student:ExportStudent;studentId:string;onClose:()=>void}){
 const {db,user,notify}=useApp();const [title,setTitle]=useState('تقرير متابعة الطالب');const [summary,setSummary]=useState('');const [recommendation,setRecommendation]=useState('');const [busy,setBusy]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{let active=true;void supabase!.from('student_report_drafts').select('title,summary,recommendation').eq('student_id',studentId).eq('teacher_id',user!.id).maybeSingle().then(r=>{if(!active)return;if(r.error)setError('تعذر تحميل مسودة التقرير');else if(r.data){setTitle(r.data.title);setSummary(r.data.summary);setRecommendation(r.data.recommendation)}setBusy(false)});return()=>{active=false}},[studentId,user?.id]);
 const local=db.students.find(s=>s.remoteId===studentId);const records=Object.values(db.evaluations).filter(e=>e.studentId===local?.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const document=studentReportDocument(student,db.settings.school,db.settings.logo,{title,summary,recommendation,teacher:user?.name||'',records:records.map(e=>({date:evaluationDate(e,db.settings.termStartDate),track:e.track,grade:e.grade,score:e.scores[0],feedback:e.writtenFeedback||e.notes||''}))});
 const save=async()=>{setBusy(true);setError('');const r=await supabase!.from('student_report_drafts').upsert({student_id:studentId,teacher_id:user!.id,title,summary,recommendation});setBusy(false);if(r.error)setError('تعذر حفظ مسودة التقرير');else notify('تم حفظ مسودة تقرير الطالب')};
 return <Modal title={'تقرير الطالب • '+student.name} onClose={onClose}><p>عدّل العنوان والملخص والتوصيات؛ نتائج التقييم تُعرض من السجلات المحفوظة.</p><Field label="عنوان التقرير"><input maxLength={150} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="ملخص المعلم"><textarea rows={3} maxLength={3000} value={summary} onChange={e=>setSummary(e.target.value)}/></Field><Field label="التوصيات والتحفيز"><textarea rows={3} maxLength={3000} value={recommendation} onChange={e=>setRecommendation(e.target.value)}/></Field>{error&&<p role="alert">{error}</p>}<div className="row-actions"><Button disabled={busy||!title.trim()} onClick={()=>void save()}>حفظ مسودة التقرير</Button><Button variant="gold" disabled={busy||!title.trim()} onClick={()=>saveStudentFile(document,'تقرير الطالب.html','text/html;charset=utf-8')}>تنزيل للطباعة / PDF</Button></div><iframe title="معاينة تقرير الطالب" sandbox="" style={{width:'100%',height:420,border:0,marginTop:16}} srcDoc={document}/></Modal>;
}
