import {useRef,useState} from 'react';
import {supabase} from '../services/supabase';
import {Button,Field,Modal,Badge} from './ui';
type ClassRow={id:string;program_id:string;stage:string;grade:string;section:string;active:boolean};
type Match={id:string;full_name:string;program_id:string;class_id:string;active:boolean;stage:string;grade:string;section:string;enrollments:{program_id:string;class_id:string;active:boolean}[]};
const program=(id:string)=>id==='diploma'?'الدبلوما':'ثنائي اللغة';
const section=(value:string)=>value&&value!=='غير موزع'?' • شعبة '+value:'';
export default function StudentPathways({classes,onClose,onSaved}:{classes:ClassRow[];onClose:()=>void;onSaved:()=>Promise<void>}){
 const [term,setTerm]=useState('');const [matches,setMatches]=useState<Match[]>([]);const [chosen,setChosen]=useState<Match|null>(null);const [destination,setDestination]=useState('');const [mode,setMode]=useState('add');const [searching,setSearching]=useState(false);const [saving,setSaving]=useState(false);const [searched,setSearched]=useState(false);const [error,setError]=useState('');const request=useRef(0);
 const normalized=(value:string)=>value.replace(/[أإآٱ]/g,'ا').replace(/[\sـًٌٍَُِّْ]/g,'');
 const destinations=chosen?classes.filter(c=>c.active&&normalized(c.stage)===normalized(chosen.stage)&&normalized(c.grade)===normalized(chosen.grade)):[];
 const target=destinations.find(c=>c.id===destination);const existing=chosen?.enrollments.find(e=>e.program_id===target?.program_id);
 const search=async()=>{const ticket=++request.current;setSearching(true);setError('');setChosen(null);setMatches([]);setSearched(false);try{const r=await supabase!.rpc('find_pathway_students',{term:term.trim()});if(ticket!==request.current)return;if(r.error)throw r.error;setMatches(r.data||[]);setSearched(true)}catch{if(ticket===request.current)setError('تعذر البحث. تحقق من الاتصال وأعد المحاولة.')}finally{if(ticket===request.current)setSearching(false)}};
 const save=async()=>{if(!chosen||!target)return;setSaving(true);setError('');try{const r=await supabase!.rpc('place_pathway_student',{source_id:chosen.id,destination_id:target.id,placement:mode});if(r.error){setError(r.error.message);return}await onSaved()}catch{setError('تعذر إكمال العملية؛ حدّث القائمة قبل إعادة المحاولة.')}finally{setSaving(false)}};
 return <Modal title="إضافة أو نقل طالب بين المسارات" onClose={()=>!saving&&onClose()}><form onSubmit={e=>{e.preventDefault();void search()}}><Field label="البحث في طلاب المدرسة"><input value={term} maxLength={150} disabled={saving} onChange={e=>{request.current++;setTerm(e.target.value);setMatches([]);setChosen(null);setSearched(false);setSearching(false);setDestination('');setError('')}} placeholder="اسم الطالب (3 أحرف) أو رقمه الوطني كاملًا"/></Field><Button type="submit" disabled={saving||searching||term.trim().length<3}>{searching?'جارٍ البحث…':'بحث عن الطالب'}</Button></form><p className="form-help">اختر تسجيل الطالب الحالي، ثم شعبة من شعبك في صفه نفسه. لا تظهر تقييماته أو بيانات أسرته في البحث.</p><div className="pathway-results">{matches.map(s=><button type="button" disabled={saving} key={s.id} className={chosen?.id===s.id?'selected':''} onClick={()=>{setChosen(s);setDestination('');setMode('add');setError('')}}><b>{s.full_name}</b><span>{program(s.program_id)} • {s.stage} • {s.grade}{section(s.section)}</span><Badge tone={s.active?'green':'amber'}>{s.active?'نشط':'مؤرشف'}</Badge></button>)}</div>{searched&&!matches.length&&<p role="status">لا توجد نتائج. جرّب الاسم أو الرقم الوطني كاملًا.</p>}{matches.length===20&&<p className="form-help">تظهر أول 20 نتيجة؛ اكتب اسمًا أدق للوصول للطالب.</p>}{chosen&&<><Field label="المسار والشعبة المستهدفة"><select value={destination} disabled={saving} onChange={e=>{setDestination(e.target.value);setError('')}}><option value="">اختر من شعبك</option>{destinations.map(c=><option key={c.id} value={c.id}>{program(c.program_id)} • {c.stage} • {c.grade}{section(c.section)}</option>)}</select></Field>{!destinations.length&&<p className="form-alert">لا توجد شعبة في صف هذا الطالب ضمن شعبك. يحدد المشرف الشعبة المناسبة لحسابك.</p>}<Field label="الإجراء"><select value={mode} disabled={saving} onChange={e=>{setMode(e.target.value);setError('')}}><option value="add">إضافة مع إبقاء تسجيله الحالي</option><option value="move">نقل إلى الشعبة المختارة</option></select></Field>{target&&<div className="pathway-summary"><b>{chosen.full_name}</b><p>من {program(chosen.program_id)} • {chosen.grade}{section(chosen.section)}</p><p>إلى {program(target.program_id)} • {target.grade}{section(target.section)}</p><p>{mode==='move'&&chosen.program_id!==target.program_id?'يُؤرشف تسجيل المسار السابق وتبقى تقييماته وتسجيلاته محفوظة.':'يبقى التسجيل الحالي محفوظًا؛ لا يُنشأ قيد مكرر في المسار نفسه.'}</p>{existing&&<p>يوجد قيد في المسار المستهدف؛ سيُستخدم دون إنشاء قيد مكرر.{existing.active&&existing.class_id!==target.id?' اختر النقل لتغيير شعبته.':''}</p>}<small>يظل رقم دخول ولي الأمر وحسابه كما هما؛ تُطبق خطة الشعبة المستهدفة.</small></div>}<Button variant="gold" disabled={saving||!target||mode==='add'&&Boolean(existing?.active&&existing.class_id!==target?.id)} onClick={()=>void save()}>{saving?'جارٍ الحفظ…':mode==='move'?'تأكيد النقل':'تأكيد الإضافة'}</Button></>}{error&&<p className="form-alert" role="alert">{error}</p>}</Modal>;
}
