import React,{useEffect,useRef} from 'react';
import {X,Search,Inbox,ChevronLeft,Plus,ArrowUpLeft} from 'lucide-react';
import {useApp} from '../services/store';
import {attendanceRate} from '../utils/domain.mjs';
export function Button({children,variant='',className='',...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:string}){return <button className={`btn ${variant} ${className}`} {...props}>{children}</button>}
export function Panel({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`panel ${className}`}>{children}</section>}
export function Badge({children,tone=''}:{children:React.ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
export function Avatar({name,size='',src}:{name:string;size?:string;src?:string}){return <span className={`avatar ${size}`}>{src?<img src={src} alt="صورة حسابي"/>:name.split(' ').slice(0,2).map(x=>x[0]).join('')}</span>}
export function PageTitle({eyebrow='غراس • مساحة للعلم والإنجاز',title,subtitle,action}:{eyebrow?:string;title:string;subtitle?:string;action?:React.ReactNode}){return <div className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}
export function Empty({text='لا توجد نتائج مطابقة',action}:{text?:string;action?:React.ReactNode}){return <div className="empty"><Inbox size={36}/><h3>{text}</h3><p>ستظهر السجلات هنا عندما تتوفر.</p>{action}</div>}
export function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{React.isValidElement(children)&&typeof children.type==='string'&&['input','textarea','select'].includes(children.type)?React.cloneElement(children as React.ReactElement<Record<string,unknown>>,{'aria-label':label}):children}</label>}
export function SearchInput({value,onChange,placeholder='ابحث بالاسم أو الرقم الأكاديمي'}:{value:string;onChange:(s:string)=>void;placeholder?:string}){return <div className="search-input"><Search size={18}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></div>}
export function Modal({title,onClose,children,className=''}:{title:string;onClose:()=>void;children:React.ReactNode;className?:string}){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const last=document.activeElement as HTMLElement;const focusable=()=>Array.from(ref.current?.querySelectorAll<HTMLElement>('button,input,select,textarea,a[href],[tabindex="0"]')||[]).filter(el=>!(el as HTMLButtonElement).disabled);focusable()[0]?.focus();const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const items=focusable(),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',handler);const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',handler);document.body.style.overflow=previous;last?.focus()}},[]);
 return <div className="modal-backdrop" onClick={e=>e.target===e.currentTarget&&onClose()}><div ref={ref} className={'modal '+className} role="dialog" aria-modal="true" aria-label={title}><div className="section-head"><h2>{title}</h2><button className="icon-btn" aria-label="إغلاق" onClick={onClose}><X/></button></div>{children}</div></div>
}
export function StudentSelect({value,onChange}:{value:number;onChange:(n:number)=>void}){const {students}=useApp();return <select aria-label="اختيار الطالب" value={value} onChange={e=>onChange(Number(e.target.value))}>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>}
export function ClassSelect({value,onChange,all=true}:{value:number;onChange:(n:number)=>void;all?:boolean}){const {db,students}=useApp();return <select aria-label="اختيار الفصل" value={value} onChange={e=>onChange(Number(e.target.value))}>{all&&<option value={0}>جميع الفصول</option>}{db.classes.filter(c=>students.some(s=>s.classId===c.id)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}
export function Progress({value,label}:{value:number;label?:string}){return <div className="progress-wrap">{label&&<div><span>{label}</span><b>{value}%</b></div>}<div className="progress"><i style={{width:`${Math.min(100,Math.max(0,value))}%`}}/></div></div>}
export function StudentLink({id}:{id:number}){const {db,navigate,selectStudent}=useApp();const s=db.students.find(s=>s.id===id);return s?<button className="student-link" onClick={()=>{selectStudent(id);navigate('profile')}}><Avatar name={s.name}/><span><b>{s.name}</b><small>{s.academicId}</small></span></button>:null}
export function StudentRate({id}:{id:number}){const {db}=useApp();return <>{attendanceRate(Object.values(db.attendance).filter(a=>a.studentId===id))}%</>}
export function SectionHead({title,description,action}:{title:string;description?:string;action?:React.ReactNode}){return <div className="section-head"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</div>}
export function Pagination({page,setPage,count,size=10}:{page:number;setPage:(n:number)=>void;count:number;size?:number}){return <div className="pagination"><span>{count} سجل • الصفحة {page} من {Math.max(1,Math.ceil(count/size))}</span><div><Button disabled={page<=1} onClick={()=>setPage(page-1)}>السابق</Button><Button disabled={page*size>=count} onClick={()=>setPage(page+1)}>التالي <ChevronLeft size={16}/></Button></div></div>}
export const AddIcon=Plus;
export const GoIcon=ArrowUpLeft;

