import {useEffect,useRef,useState} from 'react';
import {BookOpen,Play,Pause,ChevronLeft,ChevronRight,Volume2,VolumeX,X} from 'lucide-react';
import type {WelcomeConfig,WelcomePassage} from '../data/welcome';
import {alafasyVerseUrl,chosenPassage} from '../utils/welcome.mjs';
import {riyadhDate} from '../utils/school-calendar.mjs';
export default function WelcomeQuran({config,preview=false}:{config:WelcomeConfig;preview?:boolean}){
 const [passages,setPassages]=useState<WelcomePassage[]>([]);const [index,setIndex]=useState(0);const [closed,setClosed]=useState(false);const [playing,setPlaying]=useState(false);const [waiting,setWaiting]=useState(false);const [muted,setMuted]=useState(false);const [error,setError]=useState('');
 const audio=useRef<HTMLAudioElement>(null);const intent=useRef(!preview&&config.welcome_autoplay);
 const passage=passages.find(p=>p.id===chosenPassage(config.welcome_presets,config.welcome_mode,riyadhDate()));const verse=passage?.verses[index];const url=verse?alafasyVerseUrl(verse.surah,verse.ayah):'';
 useEffect(()=>{const controller=new AbortController();fetch(import.meta.env.BASE_URL+'welcome-verses.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setPassages).catch(()=>{});return()=>controller.abort()},[]);
 useEffect(()=>{setIndex(0);setClosed(false)},[passage?.id]);
 const play=()=>{const player=audio.current;if(!player)return;setError('');intent.current=true;void player.play().catch(()=>{intent.current=false;setPlaying(false);setWaiting(false);setError('تعذر تشغيل التلاوة. اضغط للاستماع مجددًا.')})};
 useEffect(()=>{const player=audio.current;if(!player||!url)return;player.volume=config.welcome_volume;setError('');setPlaying(false);setWaiting(false);if(intent.current)void player.play().catch(()=>{setPlaying(false);setWaiting(false)});return()=>player.pause()},[url,config.welcome_volume]);
 const advance=()=>{if(!passage)return;if(index+1<passage.verses.length)setIndex(index+1);else if(config.welcome_repeat&&passage.verses.length>1)setIndex(0);else{intent.current=false;setPlaying(false);setWaiting(false)}};
 if(!config.welcome_enabled||closed||!verse||!passage)return null;
 return <section className={'welcome-quran '+(playing?'is-playing':'')} aria-label="آيات البداية"><div className="welcome-quran-top"><span><BookOpen size={15}/> آيات من القرآن الكريم</span>{!preview&&<button type="button" aria-label="إخفاء الآية لهذه الزيارة" onClick={()=>{audio.current?.pause();intent.current=false;setClosed(true)}}><X size={15}/></button>}</div><div className="welcome-arch" aria-hidden="true"><span>✦</span></div>{verse.basmalah&&<p className="welcome-basmalah" lang="ar">{verse.basmalah}</p>}<p className="welcome-verse" lang="ar">{verse.text}<span className="welcome-verse-number">{verse.ayah.toLocaleString('ar-SA')}</span></p><div className="welcome-reference">{passage.reference} <span>•</span> {index+1} / {passage.verses.length}</div><div className="welcome-player"><button type="button" aria-label="الآية السابقة" disabled={index===0} onClick={()=>setIndex(index-1)}><ChevronRight size={18}/></button><button type="button" className="welcome-play" onClick={()=>{if(playing){intent.current=false;audio.current?.pause()}else play()}} aria-label={playing?'إيقاف التلاوة مؤقتًا':'استمع بصوت مشاري العفاسي'}>{playing?<Pause size={18}/>:<Play size={18}/>}<span>{waiting?'جارٍ تحميل التلاوة…':playing?'إيقاف مؤقت':'استمع للتلاوة'}</span></button><button type="button" aria-label="الآية التالية" disabled={index===passage.verses.length-1} onClick={()=>setIndex(index+1)}><ChevronLeft size={18}/></button><button type="button" aria-label={muted?'تفعيل الصوت':'كتم الصوت'} aria-pressed={muted} onClick={()=>setMuted(!muted)}>{muted?<VolumeX size={18}/>:<Volume2 size={18}/>}</button></div><small className="welcome-reciter">مشاري راشد العفاسي</small>{config.welcome_caption&&<p className="welcome-caption">{config.welcome_caption}</p>}{error&&<p role="status" className="welcome-audio-error">{error}</p>}<audio ref={audio} src={url} preload="none" muted={muted} loop={config.welcome_repeat&&passage.verses.length===1} onPlaying={()=>{setPlaying(true);setWaiting(false)}} onPause={()=>{setPlaying(false);setWaiting(false)}} onWaiting={()=>setWaiting(true)} onEnded={advance} onError={()=>{intent.current=false;setPlaying(false);setWaiting(false);setError('التلاوة غير متاحة الآن. يمكنك متابعة الدخول.')}}/></section>;
}
